## Define a function

In [1]:
# Dependencies
import openml
import pandas as pd
from IPython.display import display

# Function to visualize datasets form OpenML
def download_openml_dataset(dataset_id):
    # This line will download the dataset from OpenML
    dataset = openml.datasets.get_dataset(dataset_id)

    # Get the predictors and target as a pandas DataFrame and Series, respectively
    X, y, categorical_indicator, attribute_names = dataset.get_data(
        dataset_format='dataframe',
        target=dataset.default_target_attribute
    )

    # Display the first few rows of the DataFrame
    pd.set_option('display.max_columns', 50)  # this will display up to 50 columns
    display(X.head())

    # Print the total number of rows
    print("\nTotal number of rows in X:", X.shape[0])

    # Additional metrics for 'y'
    target_name = dataset.default_target_attribute
    print(f"\nTarget variable ('y') is '{target_name}' with the following metrics:")
    print("Min of 'y':", y.min())
    print("Max of 'y':", y.max())
    print("Average of 'y':", y.mean())

    # Return the predictors and target
    return X, y

## Red wine data, 44972

In [2]:
X, y = download_openml_dataset(44972)

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4

Total number of rows in X: 1599

Target variable ('y') is 'quality' with the following metrics:
Min of 'y': 3
Max of 'y': 8
Average of 'y': 5.6360225140712945

## Wine reviews, 42074

In [3]:
X, y = download_openml_dataset(42074)

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,None,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,None,Provence red blend,Domaine de la Bégude

Total number of rows in X: 150930

Target variable ('y') is 'None' with the following metrics:

AttributeError: 'NoneType' object has no attribute 'min'

## Wine reviews, 43600

In [4]:
X, y = download_openml_dataset(43600)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_photo,taster_twitter_handle,title,variety,vintage,winery
0,Portugal,This is a deliciously creamy wine with light w...,Assobio Branco,87,14.0,Douro,None,None,Roger Voss,https://253qv1sx4ey389p9wtpp9sj0-wpengine.netd...,vossroger,Quinta dos Muras 2016 Assobio Branco White (Do...,Portuguese White,2016,Quinta dos Muras
1,US,"Black plum juice, black pepper, caramel and sm...",None,87,25.0,California,Paso Robles,Central Coast,Matt Kettmann,https://253qv1sx4ey389p9wtpp9sj0-wpengine.netd...,mattkettmann,Western Slope 2014 Cabernet Sauvignon (Paso Ro...,Cabernet Sauvignon,2014,Western Slope
2,Georgia,Aromas of green apple and white flowers prepar...,None,87,14.0,Lechkhumi,None,None,Mike DeSimone,https://253qv1sx4ey389p9wtpp9sj0-wpengine.netd...,worldwineguys,Teliani Valley 2015 Tsolikouri (Lechkhumi),Tsolikouri,2015,Teliani Valley
3,Kosovo,"This wine has aromas of black berry, dried red...",None,87,13.0,Rahoveci Valley,None,None,Jeff Jenssen,https://253qv1sx4ey389p9wtpp9sj0-wpengine.netd...,worldwineguys,Stone Castle 2013 Shiraz (Rahoveci Valley),Shiraz,2013,Stone Castle
4,Italy,"A blend of organically cultivated Groppello, M...",San'Emiliano Chiaretto,87,13.0,Lombardy,Valtnesi,None,Kerin OKeefe,https://253qv1sx4ey389p9wtpp9sj0-wpengine.netd...,kerinokeefe,Pratello 2016 San'Emiliano Chiaretto Rosato (V...,Rosato,2016,Pratello

Total number of rows in X: 81115

Target variable ('y') is 'None' with the following metrics:

AttributeError: 'NoneType' object has no attribute 'min'

# global wine points, from data.world

In [5]:
df = pd.read_excel('https://query.data.world/s/7dgdguhyvdg7gayzoavk2cz5waec45?dws=00000')
display(df.head())
print("\nTotal number of rows in X:", df.shape[0])

,Vintage,Country,County,Designation,Points,Price,Province,Title,Variety,Winery
0,1919-01-01 00:00:00,Spain,Cava,1919 Brut Selecció,88,$13.00,Catalonia,L'Arboc NV 1919 Brut Selecció Sparkling (Cava),Sparkling Blend,L'Arboc
1,1929-01-01 00:00:00,Italy,Vernaccia di San Gimignano,NaN,87,$14.00,Tuscany,Guidi 1929 2015 Vernaccia di San Gimignano,Vernaccia,Guidi 1929
2,1929-01-01 00:00:00,Italy,Sangiovese di Romagna Superiore,Prugneto,84,$15.00,Central Italy,Poderi dal Nespoli 1929 2011 Prugneto (Sangiov...,Sangiovese,Poderi dal Nespoli 1929
3,1934-01-01 00:00:00,Portugal,NaN,Reserva Velho,93,$495.00,Colares,Adega Viuva Gomes 1934 Reserva Velho Red (Cola...,Ramisco,Adega Viuva Gomes
4,1945-01-01 00:00:00,France,Rivesaltes,Legend Vintage,95,$350.00,Languedoc-Roussillon,Gérard Bertrand 1945 Legend Vintage Red (Rives...,Red Blend,Gérard Bertrand

Total number of rows in X: 24997

-------------------------------------------------------------------------------

## Gun violence, School Shootings, https://www.gunviolencearchive.org/

In [7]:
# Read the CSV data
df = pd.read_csv('/Users/a/Desktop/ClassFolder_040123/final_project/school_shootings.csv')

# Display the first few rows of the DataFrame
print("\nTotal number of rows in df:", df.shape[0])
display(df.sample(30))

Total number of rows in df: 2000

,Incident ID,Incident Date,State,City Or County,Address,# Victims Injured,# Victims Killed,# Subjects-Suspects Injured,# Subjects-Suspects Killed,# Subjects-Suspects Arrested,Operations
766,2447895,"October 28, 2022",Oklahoma,Yukon,10901 SW 15th St,0,0,0,0,1,NaN
375,2529696,"February 17, 2023",Nevada,Las Vegas,333 S Pavilion Center Dr,0,0,0,0,1,NaN
43,2594470,"May 10, 2023",Michigan,Grand Rapids,863 7th St NW,0,0,0,0,0,NaN
1890,2162602,"October 29, 2021",Virginia,Chesapeake,4410 Airline Blvd,0,0,0,0,0,NaN
1043,2412964,"September 12, 2022",Texas,Corpus Christi,3900 Hamlin Dr,0,0,0,0,0,NaN
1224,2327173,"June 9, 2022",Mississippi,Byhalia,278 MS-309,0,0,0,0,1,NaN
1939,2146097,"October 19, 2021",Indiana,Indianapolis,1200 block of Campus Dr,0,1,0,0,0,NaN
1199,2385453,"August 5, 2022",Indiana,Lafayette,1801 S 18th St,0,0,0,0,1,NaN
1767,2185675,"December 3, 2021",California,Lancaster,3730 E Avenue J,0,0,0,0,0,NaN
1661,2214981,"January 19, 2022",Georgia,Atlanta,551 John Wesley Dobbs Ave NE,0,0,0,0,0,NaN
1169,2391670,"August 18, 2022",Louisiana,Slidell,300 Spartan Dr,0,0,0,0,1,NaN
1906,2153322,"October 27, 2021",Missouri,Saint Louis,918 Prigge Rd,0,0,0,0,0,NaN
1925,2148080,"October 21, 2021",Georgia,Savannah,9520 Ferguson Ave,0,0,0,0,1,NaN
708,2460711,"November 15, 2022",Illinois,Aurora,1201 W New York St,0,0,0,0,1,NaN
1895,2153994,"October 28, 2021",Michigan,Addison,219 N Comstock St,0,0,0,0,1,NaN
1122,2403135,"August 27, 2022",Indiana,Fort Wayne,475 E State Blvd,0,0,0,0,1,NaN
1419,2276298,"April 11, 2022",Arkansas,Pine Bluff,711 W 11th Ave,0,0,0,0,0,NaN
1342,2294626,"May 4, 2022",Minnesota,Duluth,11 E Superior St,0,0,0,0,1,NaN
441,2519443,"February 6, 2023",Wisconsin,Oshkosh,915 Hazel St,0,0,0,0,0,NaN
1896,2153854,"October 28, 2021",Texas,Grand Prairie,1160 Warrior Dr,0,0,0,0,0,NaN
1104,2402664,"August 30, 2022",South Carolina,Rock Hill,4757 Mt Gallant Rd,0,0,0,0,1,NaN
118,2580125,"April 24, 2023",Oklahoma,Oklahoma City (Midwest City),6420 SE 15th St,0,1,0,0,1,NaN
1909,2153116,"October 26, 2021",Georgia,Jesup,1425 W Orange St,0,0,0,0,0,NaN
273,2547884,"March 16, 2023",North Carolina,Monroe,1 High School Dr,0,0,0,0,1,NaN
13,2602362,"May 18, 2023",Illinois,Pleasant Hill,501 E Quincy St,0,0,0,0,1,NaN
1944,2145405,"October 18, 2021",Georgia,Albany,2400 Gillionville Rd,0,0,0,0,0,NaN
765,2449060,"October 28, 2022",Missouri,Columbia,700 E Stadium Blvd,0,0,0,1,0,NaN
1296,2306001,"May 18, 2022",Tennessee,Murfreesboro,2650 Middle Tennessee Blvd,1,1,0,0,1,NaN
1629,2222122,"January 28, 2022",North Carolina,Lumberton,3901 Fayetteville Rd,0,0,0,0,1,NaN
1992,2133876,"October 5, 2021",Connecticut,Hamden,2040 Dixwell Ave,0,0,0,0,1,NaN

## Gun violence, Mass Shootings, https://www.gunviolencearchive.org/

In [8]:
# Read the CSV data
df = pd.read_csv('/Users/a/Desktop/ClassFolder_040123/final_project/mass_shooting_all_years.csv')

# Display the first few rows of the DataFrame
print("\nTotal number of rows in df:", df.shape[0])
display(df.sample(30))

Total number of rows in df: 2000

,Incident ID,Incident Date,State,City Or County,Address,# Victims Injured,# Victims Killed,# Subjects-Suspects Injured,# Subjects-Suspects Killed,# Subjects-Suspects Arrested,Operations
1726,1800188,"September 19, 2020",New Jersey,Plainfield,523 W 3rd St,4,0,0,0,0,NaN
1695,1815308,"October 5, 2020",District of Columbia,Washington,400 block of Orange St SE,3,1,0,0,0,NaN
293,2459150,"November 13, 2022",Virginia,Charlottesville,130 Culbreth St,2,3,0,0,1,NaN
1401,1993664,"May 2, 2021",Pennsylvania,Philadelphia,5200 block of Burton St,3,1,0,0,0,NaN
1778,1780091,"August 30, 2020",Kentucky,Madisonville,400 block of Elm St,5,0,0,0,0,NaN
1634,1850693,"November 12, 2020",North Carolina,Gastonia,1225 Union Rd,6,0,0,0,2,NaN
1633,1850981,"November 12, 2020",Florida,Tampa,1200 block of E Palifox St,4,2,0,0,0,NaN
354,2436826,"October 13, 2022",North Carolina,Raleigh,5300 block of Sahalee Way,2,5,1,0,1,NaN
244,2490925,"December 30, 2022",Texas,Humble,4800 block of Park Square Ln,3,2,0,0,0,NaN
1433,1979869,"April 15, 2021",Louisiana,Lake Charles,4101 5th Ave,3,1,0,0,1,NaN
1015,2155043,"October 14, 2021",Mississippi,Mccomb,1300 14th St,6,0,0,0,0,NaN
1265,2050167,"June 30, 2021",Delaware,Dover,100 block of S New St,3,1,0,0,0,NaN
1806,1767747,"August 18, 2020",Illinois,Rockford,3001 Harney Ct,4,0,0,0,0,NaN
1113,2104725,"August 31, 2021",North Carolina,Elm City,3500 block of London Church Rd,2,2,0,0,1,NaN
1649,1840364,"November 1, 2020",Oklahoma,Oklahoma City,10601 S Western Ave,3,1,0,0,0,NaN
808,2248066,"March 6, 2022",Pennsylvania,Hazleton,182 S Wyoming St,4,1,0,0,1,NaN
768,2269745,"April 3, 2022",California,San Francisco,670 Brunswick St,2,2,0,0,0,NaN
194,2513517,"January 28, 2023",South Carolina,Andrews,Birch Creek Rd,2,2,0,0,1,NaN
1797,1772680,"August 23, 2020",Tennessee,Somerville,1100 block of Brewer Rd,4,1,0,0,7,NaN
519,2368029,"July 24, 2022",Georgia,Atlanta,1695 Northside Dr NW,8,0,0,0,0,NaN
219,2499119,"January 9, 2023",Minnesota,Minneapolis,2218 E Lake St,4,0,0,0,0,NaN
702,2299176,"May 10, 2022",Texas,Brookshire,Purdy and 4th St,3,1,0,0,0,NaN
912,2190367,"December 12, 2021",Florida,Tampa,Alaska Ave,5,0,0,0,1,NaN
1785,1777180,"August 26, 2020",Michigan,Pontiac,252 Carriage Circle Dr,1,3,0,0,1,NaN
452,2397504,"August 25, 2022",Washington,Spokane,701 N Chestnut St,4,0,0,0,0,NaN
735,2286089,"April 23, 2022",California,San Bernardino,1036 W Highland Ave,4,1,0,0,0,NaN
1144,2091597,"August 15, 2021",Texas,San Antonio,1621 S New Braunfels Ave,2,3,0,0,2,NaN
1558,1899819,"January 11, 2021",Florida,Miami,2491 NE 58th St,4,0,0,0,0,NaN
233,2494254,"January 3, 2023",District of Columbia,Washington,6200 block of Georgia Ave NW,3,1,0,0,0,NaN
1747,1787655,"September 7, 2020",New York,Brooklyn,Norstrand Ave and Crown St,5,0,0,0,2,NaN

## Firearm deaths, USA, data.world

In [9]:
# Read the CSV data
df = pd.read_csv('/Users/a/Desktop/ClassFolder_040123/final_project/firearm_deaths_usafacts.csv')

# Display the first few rows of the DataFrame
display(df.sample(30))
print("\nTotal number of rows in df:", df.shape[0])

,Years,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
30,Colorado (People),486,417,483,465,474,509,430,462.0,399.0,422.0,429.0,498.0,544.0,511.0,505.0,536.0,465.0,449.0,452.0,443.0,510.0,517.0,501.0,553.0,535.0,497.0,505.0,513.0,583.0,555.0,573.0,672.0,619.0,663.0,701.0,812.0,779.0,889.0,846.0,922.0,1064.0
60,Ohio (People),1366,1220,1054,1112,1127,1097,1061,1074.0,1137.0,1178.0,1284.0,1232.0,1239.0,1175.0,1055.0,1008.0,966.0,969.0,939.0,890.0,1029.0,1069.0,934.0,1036.0,1116.0,1114.0,1105.0,1115.0,991.0,1148.0,1227.0,1263.0,1289.0,1211.0,1397.0,1524.0,1589.0,1555.0,1578.0,1764.0,1911.0
44,Maine (People),111,92,103,109,121,86,113,132.0,138.0,114.0,123.0,125.0,114.0,119.0,109.0,123.0,94.0,122.0,113.0,112.0,98.0,88.0,82.0,108.0,109.0,105.0,107.0,122.0,122.0,113.0,136.0,130.0,158.0,133.0,144.0,123.0,172.0,159.0,163.0,153.0,178.0
36,Hawaii (People),58,43,45,52,50,59,66,46.0,59.0,56.0,57.0,55.0,51.0,79.0,75.0,48.0,58.0,40.0,42.0,52.0,47.0,36.0,37.0,41.0,28.0,33.0,36.0,41.0,47.0,45.0,49.0,51.0,38.0,40.0,55.0,66.0,39.0,59.0,62.0,50.0,71.0
27,Arizona (People),519,501,472,522,550,616,647,674.0,666.0,699.0,696.0,745.0,811.0,902.0,986.0,833.0,853.0,887.0,822.0,796.0,842.0,968.0,849.0,897.0,934.0,982.0,951.0,907.0,856.0,931.0,964.0,946.0,941.0,927.0,970.0,1094.0,1134.0,1147.0,1136.0,1265.0,1365.0
69,Utah (People),166,190,168,176,164,190,194,169.0,172.0,201.0,214.0,195.0,197.0,224.0,225.0,213.0,209.0,242.0,192.0,193.0,229.0,207.0,230.0,225.0,227.0,224.0,253.0,238.0,260.0,314.0,308.0,324.0,339.0,337.0,367.0,370.0,410.0,397.0,394.0,429.0,450.0
76,Sources:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Connecticut (People),238,245,227,205,211,234,235,275.0,278.0,258.0,287.0,271.0,304.0,299.0,255.0,247.0,188.0,190.0,199.0,179.0,191.0,147.0,153.0,173.0,187.0,173.0,149.0,200.0,173.0,209.0,210.0,227.0,161.0,187.0,189.0,172.0,188.0,186.0,190.0,219.0,248.0
9,20-34 (People),14667,13670,12691,12470,12430,13402,12887,13417.0,13656.0,14781.0,15414.0,15078.0,15801.0,15169.0,13571.0,12219.0,11625.0,10549.0,9874.0,9758.0,10301.0,10446.0,10565.0,10067.0,10500.0,10535.0,10535.0,10297.0,9757.0,10042.0,10250.0,10632.0,10680.0,10427.0,11908.0,12966.0,13125.0,12704.0,12880.0,16270.0,17483.0
25,Alabama (People),824,820,710,750,743,812,749,801.0,801.0,912.0,928.0,873.0,943.0,945.0,931.0,870.0,848.0,819.0,790.0,766.0,737.0,724.0,765.0,679.0,736.0,780.0,812.0,820.0,830.0,782.0,785.0,831.0,860.0,815.0,958.0,1046.0,1124.0,1064.0,1076.0,1141.0,1315.0
51,Montana (People),139,121,125,133,135,155,137,122.0,130.0,151.0,144.0,124.0,144.0,151.0,161.0,156.0,151.0,118.0,123.0,134.0,160.0,134.0,145.0,125.0,161.0,120.0,139.0,155.0,166.0,164.0,167.0,171.0,172.0,172.0,205.0,194.0,244.0,186.0,209.0,238.0,280.0
63,Pennsylvania (People),1227,1195,1018,1131,1147,1122,1173,1162.0,1266.0,1387.0,1302.0,1317.0,1467.0,1319.0,1401.0,1331.0,1390.0,1247.0,1190.0,1256.0,1172.0,1220.0,1230.0,1270.0,1352.0,1371.0,1325.0,1345.0,1349.0,1307.0,1438.0,1453.0,1451.0,1390.0,1485.0,1555.0,1636.0,1654.0,1541.0,1752.0,1905.0
17,"Asian, Native Hawaiian or Other Pacifi...",220,207,232,237,248,292,292,350.0,389.0,424.0,536.0,518.0,606.0,566.0,572.0,491.0,510.0,449.0,446.0,424.0,389.0,430.0,445.0,398.0,447.0,475.0,440.0,402.0,438.0,411.0,429.0,478.0,469.0,435.0,534.0,612.0,610.0,641.0,679.0,670.0,NaN
21,By gender,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,65 + (People),3377,3799,3949,4217,4443,4758,4909,4880.0,4852.0,4980.0,4916.0,4789.0,4935.0,4734.0,4776.0,4710.0,4497.0,4514.0,4333.0,4264.0,4364.0,4402.0,4232.0,4190.0,4325.0,4183.0,4292.0,4566.0,4723.0,4703.0,4999.0,5270.0,5573.0,5864.0,6052.0,6266.0,6572.0,6988.0,6963.0,7131.0,7645.0
52,Nebraska (People),154,125,138,143,153,164,155,137.0,134.0,160.0,169.0,160.0,158.0,154.0,169.0,160.0,144.0,162.0,146.0,168.0,140.0,140.0,134.0,119.0,135.0,141.0,142.0,150.0,132.0,152.0,161.0,167.0,168.0,179.0,169.0,171.0,160.0,183.0,205.0,197.0,200.0
62,Oregon (People),336,341,354,359,331,389,349,377.0,399.0,379.0,367.0,420.0,392.0,447.0,433.0,427.0,428.0,442.0,389.0,378.0,358.0,374.0,395.0,385.0,402.0,384.0,387.0,385.0,417.0,458.0,420.0,443.0,462.0,497.0,486.0,513.0,528.0,519.0,566.0,592.0,670.0
48,Minnesota (People),271,295,290,269,279,341,310,292.0,341.0,374.0,351.0,360.0,340.0,354.0,394.0,377.0,346.0,306.0,296.0,312.0,324.0,306.0,332.0,363.0,361.0,329.0,344.0,371.0,336.0,365.0,396.0,382.0,427.0,377.0,410.0,432.0,465.0,437.0,465.0,513.0,573.0
10,35-49 (People),7213,7124,6645,6818,6836,7154,7121,7307.0,7505.0,8087.0,8317.0,8338.0,8738.0,8711.0,8243.0,8353.0,8028.0,7844.0,7330.0,7504.0,7491.0,7804.0,7593.0,7485.0,7673.0,7587.0,7673.0,7641.0,7558.0,7485.0,7400.0,7582.0,7538.0,7401.0,7846.0,8492.0,8659.0,8697.0,8767.0,9863.0,10802.0
56,New Mexico (People),263,300,236,249,269,316,306,319.0,286.0,255.0,288.0,293.0,279.0,324.0,299.0,324.0,286.0,288.0,290.0,291.0,274.0,304.0,326.0,289.0,267.0,283.0,295.0,294.0,299.0,301.0,306.0,323.0,326.0,340.0,390.0,383.0,394.0,438.0,471.0,479.0,578.0
78,NaN,Centers for Disease Control and Prevention,"WISQARS, Fatal Injury Reports, National, Regio...",NaN,https://wisqars.cdc.gov/data/explore-data/home,NaN,2020,Annual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Texas (People),3416,3430,3306,3095,3272,3358,2946,3110.0,3081.0,3479.0,3727.0,3466.0,3458.0,3405.0,2853.0,2616.0,2443.0,2438.0,2117.0,2168.0,2350.0,2301.0,2432.0,2342.0,2490.0,2422.0,2561.0,2598.0,2691.0,2714.0,2599.0,2743.0,2778.0,2848.0,3203.0,3353.0,3513.0,3522.0,3683.0,4164.0,4613.0
1,By type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,By race,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,New York (People),1950,1773,1778,1576,1571,1771,1908,2131.0,2257.0,2418.0,2515.0,2446.0,2422.0,2100.0,1638.0,1428.0,1234.0,1109.0,1016.0,1093.0,1068.0,994.0,1034.0,951.0,1019.0,1002.0,985.0,963.0,958.0,1011.0,997.0,977.0,863.0,875.0,849.0,900.0,772.0,821.0,804.0,1052.0,1078.0
2,Homicide (People),15089,13830,12040,11815,11836,13029,12657,13645.0,14464.0,16218.0,17746.0,17488.0,18253.0,17527.0,15551.0,14037.0,13252.0,11798.0,10828.0,10801.0,11348.0,11829.0,11920.0,11624.0,12352.0,12791.0,12632.0,12179.0,11493.0,11078.0,11068.0,11622.0,11208.0,11008.0,12979.0,14415.0,14542.0,13958.0,14414.0,19384.0,20958.0
79,NaN,Centers for Disease Control and Prevention,WONDER Underlying Cause of Death,Data Request,https://wonder.cdc.gov/controller/datarequest/D76,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Florida (People),2246,2253,1925,2087,2066,2145,2253,2525.0,2424.0,2411.0,2323.0,2207.0,2292.0,2216.0,2160.0,2074.0,1979.0,1902.0,1721.0,1692.0,1816.0,1886.0,1940.0,1890.0,1838.0,2083.0,2272.0,2334.0,2324.0,2268.0,2378.0,2473.0,2442.0,2410.0,2559.0,2704.0,2724.0,2902.0,2872.0,3041.0,3142.0
80,Exported on: 05/24/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,American Indian or Alaska Native (People),263,255,237,220,243,244,217,266.0,278.0,245.0,285.0,232.0,278.0,313.0,304.0,260.0,267.0,276.0,268.0,240.0,240.0,287.0,269.0,281.0,305.0,291.0,246.0,279.0,291.0,317.0,305.0,337.0,326.0,335.0,383.0,444.0,444.0,477.0,432.0,578.0,NaN

Total number of rows in df: 81

## Gun deaths by county, https://data.world/nkrishnaswami/gun-deaths-by-county

In [10]:
# Read the TSV data
df = pd.read_csv('/Users/a/Desktop/ClassFolder_040123/final_project/Gun Deaths by County, 1999-2020.tsv', sep='\t')

# Display the first few rows of the DataFrame
display(df.sample(30))
print("\nTotal number of rows in df:", df.shape[0])

,year,county_name,state_code,county_code,deaths,population,crude_rate,crude_rate_lower_95_confidence_interval,crude_rate_upper_95_confidence_interval,age_adjusted_rate,age_adjusted_rate_lower_95_confidence_interval,age_adjusted_rate_upper_95_confidence_interval
2019,2002,"Hampden County, MA",25,25013,20,458780,4.36,2.66,6.73,4.36,2.66,6.73
10318,2015,"Baldwin County, AL",1,1003,37,203709,18.16,12.79,25.04,17.62,12.27,24.50
3555,2004,"Clallam County, WA",53,53009,12,67411,NaN,9.20,31.10,NaN,7.57,29.03
1981,2002,"Pike County, KY",21,21195,14,67438,NaN,11.35,34.83,NaN,11.75,36.07
12118,2017,"Hancock County, IN",18,18059,13,74985,NaN,9.23,29.65,NaN,8.34,28.19
1869,2002,"Brevard County, FL",12,12009,52,495425,10.50,7.84,13.76,9.34,6.89,12.38
13465,2018,"Victoria County, TX",48,48469,14,92035,NaN,8.32,25.52,NaN,7.97,24.47
9818,2014,"Shawnee County, KS",20,20177,23,178406,12.89,8.17,19.34,13.27,8.32,20.10
13903,2019,"Livingston County, MI",26,26093,13,191995,NaN,3.61,11.58,NaN,3.72,12.57
7911,2011,"Muskogee County, OK",40,40101,10,71003,NaN,6.75,25.90,NaN,6.37,26.44
1880,2002,"Indian River County, FL",12,12061,12,118144,NaN,5.25,17.74,NaN,4.00,16.59
4489,2006,"Madison County, MS",28,28089,13,87844,NaN,7.88,25.31,NaN,8.31,26.68
8430,2012,"Montgomery County, MD",24,24031,39,1004709,3.88,2.76,5.31,3.80,2.67,5.24
7494,2011,"Kings County, CA",6,6031,12,153765,NaN,4.03,13.63,NaN,4.12,14.76
11538,2016,"Westchester County, NY",36,36119,27,974542,2.77,1.83,4.03,2.77,1.81,4.07
5310,2007,"Florence County, SC",45,45041,14,133757,NaN,5.72,17.56,NaN,5.56,17.07
371,1999,"Robeson County, NC",37,37155,31,122514,25.30,17.19,35.92,25.09,17.05,35.61
4116,2005,"Ector County, TX",48,48135,21,125378,16.75,10.37,25.60,18.24,11.14,28.16
4404,2006,"Johnson County, KS",20,20091,29,514813,5.63,3.77,8.09,5.75,3.82,8.31
1176,2001,"Lauderdale County, AL",1,1077,10,87791,NaN,5.46,20.95,NaN,5.45,20.92
2262,2002,"Richland County, SC",45,45079,42,331285,12.68,9.14,17.14,12.16,8.72,16.49
14472,2020,"Santa Cruz County, CA",6,6087,13,269925,NaN,2.56,8.24,NaN,2.29,7.73
5957,2008,"Florence County, SC",45,45041,20,135032,14.81,9.05,22.87,14.07,8.47,21.98
1084,2000,"Denton County, TX",48,48121,22,432976,5.08,3.18,7.69,6.54,3.88,10.34
8156,2012,"Shelby County, AL",1,1117,27,200941,13.44,8.85,19.55,14.03,9.24,20.41
14339,2019,"Grant County, WA",53,53025,10,97733,NaN,4.91,18.82,NaN,4.97,19.06
45,1999,"Kern County, CA",6,6029,68,655428,10.37,8.06,13.15,11.13,8.61,14.16
7651,2011,"Sedgwick County, KS",20,20173,56,501076,11.18,8.44,14.51,11.38,8.58,14.82
9360,2013,"Wagoner County, OK",40,40145,13,75700,NaN,9.14,29.37,NaN,9.30,29.88
1057,2000,"Bradley County, TN",47,47011,12,87965,NaN,7.05,23.83,NaN,7.06,23.87

Total number of rows in df: 15252

## Gun laws, https://www.kaggle.com/code/jonathanbouchet/firearm-regulations-in-the-u-s

In [11]:
# Read the CSV data
df = pd.read_csv('/Users/a/Desktop/ClassFolder_040123/final_project/raw_data.csv')

# Display the first few rows of the DataFrame
display(df.sample(30))
print("\nTotal number of rows in df:", df.shape[0])

,state,year,age18longgunpossess,age18longgunsale,age21handgunpossess,age21handgunsale,age21longgunpossess,age21longgunsale,age21longgunsaled,alcoholism,alctreatment,amm18,amm21h,ammbackground,ammlicense,ammpermit,ammrecords,ammrestrict,assault,assaultlist,assaultregister,assaulttransfer,backgroundpurge,cap14,cap16,...,residential,security,showing,stalking,statechecks,statechecksh,strawpurchase,strawpurchaseh,tenroundlimit,theft,threedaylimit,traffickingbackground,traffickingprohibited,traffickingprohibitedh,training,universal,universalh,universalpermit,universalpermith,violent,violenth,violentpartial,waiting,waitingh,lawtotal
1096,Washington,2012,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25
742,Texas,2005,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18
1124,Missouri,2013,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8
311,Idaho,1997,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6
1265,Kansas,2016,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7
1039,South Carolina,2011,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12
1173,Mississippi,2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5
471,Michigan,2000,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,26
197,West Virginia,1994,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,12
1293,Utah,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,11
1152,Arizona,2014,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11
1278,New Hampshire,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10
854,California,2008,0,1,0,1,0,0,0,1,0,1,1,0,0,0,0,1,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,93
415,Kansas,1999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15
738,Rhode Island,2005,1,1,1,1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,...,0,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,1,0,0,0,1,1,45
466,Kentucky,2000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6
149,Wyoming,1993,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7
857,Delaware,2008,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,...,0,0,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,26
704,California,2005,0,1,0,1,0,0,0,1,0,1,1,0,0,0,0,1,1,1,1,1,1,1,1,...,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,93
84,Ohio,1992,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,19
496,Washington,2000,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24
1058,Florida,2012,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,21
1291,Tennessee,2016,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22
480,New Mexico,2000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11
712,Illinois,2005,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,1,1,0,...,0,0,1,1,1,1,0,0,0,0,1,0,1,1,0,0,0,1,1,0,0,1,1,1,60
645,Virginia,2003,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,14
12,Illinois,1991,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,...,0,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,1,1,41
1175,Montana,2014,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4
418,Maine,1999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,9
888,Rhode Island,2008,1,1,1,1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,...,0,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,1,0,0,0,1,1,45

Total number of rows in df: 1350

## Gun violence, https://www.kaggle.com/datasets/nidzsharma/us-mass-shootings-19822023

In [12]:
# Read the CSV data
df = pd.read_csv('/Users/a/Desktop/ClassFolder_040123/final_project/shooting-1982-2023.csv')

# Display the first few rows of the DataFrame
display(df.sample(30))
print("\nTotal number of rows in df:", df.shape[0])

,case,location,date,summary,fatalities,injured,total_victims,location.1,age_of_shooter,prior_signs_mental_health_issues,mental_health_details,weapons_obtained_legally,where_obtained,weapon_type,weapon_details,race,gender,latitude,longitude,type,year
93,Carthage nursing home shooting,"Carthage, North Carolina",29-03-2009,"Robert Stewart, 45, opened fire at a nursing h...",8,3,11,Other,45,Yes,His estranged wife told her workplace that her...,Yes,Local sporting goods stores and individuals,"One revolver, one shotgun",Winchester 1300 pump-action shotgun; .357 Magn...,white,Male,35.333434,-79.414592,Mass,2009
58,Baton Rouge police shooting,"Baton Rouge, Lousiana",17-07-2016,"Gavin Long, 29, a former Marine who served in ...",3,3,6,Other,29,Yes,Unclear,Unknown,-,Two semiautomatic rifles; one semiautomatic ha...,"IWI Tavor SAR 5.56 caliber rifle, Springfield ...",Black,M,30.433601,-91.081403,Spree,2016
111,Xerox killings,"Honolulu, Hawaii",02-11-1999,"Byran Koji Uyesugi, 40, a Xerox service techni...",7,0,7,Workplace,40,Yes,"A psychiatrist, testifying for the prosecutio...",Yes,Hunting Supplies of Hawaii (The Armory) in Hon...,One semiautomatic handgun,9mm Glock 17 semiautomatic handgun,Asian,Male,21.320063,-157.876462,Spree,1999
89,Hartford Beer Distributor shooting,"Manchester, Connecticut",03-08-2010,"Omar S. Thornton, 34, shot up his Hartford Bee...",9,2,11,Workplace,34,No,He apparently was driven over the edge by unad...,Yes,"Gun dealer in East Windsor, Conn.",Two semiautomatic handguns,Two 9mm Ruger SR9 semiautomatic handguns,black,Male,41.798764,-72.570068,Mass,2010
85,Su Jung Health Sauna shooting,"Norcross, Georgia",21-02-2012,"Jeong Soo Paek, 59, returned to a Korean spa f...",5,0,5,Other,59,Yes,His sister worried about his homicidal tendenc...,Yes,Unknown,One semiautomatic handgun,.45-caliber semiautomatic handgun,Asian,Male,33.9412127,-84.2135309,Mass,2012
4,Virginia Walmart shooting,"Chesapeake, Virginia",11-22-22,"Andre Bing, 31, who worked as a supervisor at ...",6,6,12,Workplace,31,-,-,-,-,semiautomatic handgun,-,Black,M,-,-,Mass,2022
37,Rite Aid warehouse shooting,"Perryman, Maryland",9-20-18,"Snochia Moseley, 26, reportedly a disgruntled ...",3,3,6,Workplace,26,-,-,Yes,-,semiautomatic handgun,Glock 9 mm,Black,F,39.455658,-76.208485,Mass,2018
102,Capitol Hill massacre,"Seattle, Washington",25-03-2006,"Kyle Aaron Huff, 28, opened fire at a rave aft...",7,2,9,Other,28,No,Police were unable to find any record that he ...,Yes,"Various sporting goods stores in Kalispell, Mont.","Two semiautomatic handguns, one rifle (assault...",".40-caliber Ruger, one other semiautomatic han...",white,Male,47.6229,-122.3165,Mass,2006
139,Dallas nightclub shooting,"Dallas, Texas",29-06-1984,"Abdelkrim Belachheb, 39, opened fire at an ups...",6,1,7,Other,39,Yes,"During his last meal with his wife, he confess...",No,"Hines Boulevard Pawn Shop in Dallas, Texas",One semiautomatic handgun,9mm Smith & Wesson 459 semiautomatic handgun,white,Male,32.925166,-96.838676,Mass,1984
33,SunTrust bank shooting,"Sebring, Florida",1-23-19,"Zephen A. Xaver, 21, fatally shot five women i...",5,0,5,Workplace,21,Yes,Xaver was reported to have a lenghty history o...,Yes,-,handgun,9 mm handgun,White,M,27.471043,-81.45847,Mass,2019
80,Accent Signage Systems shooting,"Minneapolis, Minnesota",27-09-2012,"Andrew Engeldinger, 36, upon learning he was b...",7,1,8,Workplace,36,Yes,"His family worried about his ""paranoia and del...",Yes,Unknown,One semiautomatic handgun,9mm Glock semiautomatic handgun,white,Male,44.977425,-93.310408,Mass,2012
55,Fresno downtown shooting,"Fresno, California",18-04-2017,"Kori Ali Muhammad, 39, opened fire along a str...",3,0,3,Other,39,Unclear,-,Unknown,-,handgun,.357 revolver,Black,M,36.746378,-119.800319,Mass,2017
94,Atlantis Plastics shooting,"Henderson, Kentucky",25-06-2008,"Disgruntled employee Wesley Neal Higdon, 25, s...",6,1,7,Workplace,25,No,He called his girlfriend two hours before the ...,Yes,Unknown,One semiautomatic handgun,.45-caliber Hi-Point semiautomatic handgun,white,Male,37.76721,-87.5573742,Spree,2008
56,Fort Lauderdale airport shooting,"Fort Lauderdale, Florida",06-01-2017,"Esteban Santiago, 26, flew from Alaska to Fort...",5,6,11,Airport,26,Yes,"Among other signs, Santiago had gone to a FBI ...",Yes,-,semiautomatic handgun\n,Walther 9mm semi-automatic pistol[,Latino,M,26.072751,-80.143382,Mass,2017
72,Fort Hood shooting 2,"Fort Hood, Texas",03-04-2014,"Army Specialist Ivan Lopez, 34, opened fire at...",3,12,15,Military,34,Unclear,"Lopez ""had a long history of troubling behavio...",\nYes,"Local gun store in Killeen, Guns Galore",handgun\n,.45-caliber Smith & Wesson handgun,Latino,M,31.141716,-97.777559,Mass,2014
26,Odessa-Midland shooting spree,"Odessa, Texas",8-31-19,"Seth A. Ator, 36, fired at police officers who...",7,25,32,Other,36,yes,"""One friend of the family said the gunman had ...",-,-,semiautomatic rifle,-,White,M,31.925974,-102.2796,Spree,2019
97,Westroads Mall shooting,"Omaha, Nebraska",05-12-2007,"Robert A. Hawkins, 19, opened fire inside West...",9,4,13,Other,19,Yes,He had been treated in the past for depression...,No,Stolen from grandfather,One rifle (assault),WASR-10 Century Arms semiautomatic rifle,white,Male,41.265719,-96.067495,Spree,2007
31,Harry Pratt Co. warehouse shooting,"Aurora, Illinois",2-15-19,"Gary Martin, 45, went on a rampage inside the ...",5,6,11,Workplace,45,Yes,(pending),No,-,handgun,"Smith & Wesson handgun, with a green sighting ...",Black,M,41.753725,-88.331057,Mass,2019
84,Oikos University killings,"Oakland, California",02-04-2012,"One L. Goh, 43, a former student, opened fire ...",7,3,10,School,43,Yes,A former instructor at Oikos described him as ...,Yes,"Bullseye in Castro Valley, Calif.",One semiautomatic handgun,.45-caliber semiautomatic handgun,Asian,Male,37.8043808,-122.2708166,Mass,2012
109,Wakefield massacre,"Wakefield, Massachusetts",26-12-2000,"Michael McDermott, 42, opened fire on co-worke...",7,0,7,Workplace,42,Yes,"Psychiatrist guessed he had schizophrenia, but...",Yes,Unknown,"One semiautomatic handgun, one rifle (assault)...",.32-caliber Retolaza semiautomatic handgun; AK...,white,Male,42.500429,-71.075913,Mass,2000
54,Rural Ohio nursing home shooting,"Kirkersville, Ohio",12-05-2017,"Thomas Hartless, 43, shot and killed a former ...",3,0,3,Workplace,43,Yes,Hartless had a violent criminal history; his f...,TBD,-,"handgun, shotgun",-,White,M,39.959034,-82.596508,Mass,2017
135,ESL shooting,"Sunnyvale, California",16-02-1988,Former ESL Incorporated employee Richard Farle...,7,4,11,Workplace,39,Yes,He stalked and harassed his colleague Laura Bl...,Yes,Various sporting goods and gun stores in North...,"Two semiautomatic handguns, one rifle, two rev...",".380 ACP Browning, 9mm Smith & Wesson semiauto...",white,Male,37.3688301,-122.0363496,Mass,1988
103,Goleta postal shootings,"Goleta, California",30-01-2006,"Former postal worker Jennifer Sanmarco, 44, sh...",8,0,8,Workplace,44,Yes,She was placed on retirement disability for ps...,Yes,"Pawn shops in Grants and Gallup, N.M.",One semiautomatic handgun,9mm Smith & Wesson 915 semiautomatic handgun,white,Female,34.425571,-119.866069,Mass,2006
52,Pennsylvania supermarket shooting,"Tunkhannock, Pennsylvania",6-7-17,"Randy Stair, a 24-year-old worker at Weis groc...",3,0,3,Workplace,24,Unclear,-,TBD,-,shotguns,-,White,M,41.529546,-75.94722,Mass,2017
87,IHOP shooting,"Carson City, Nevada",06-09-2011,"Eduardo Sencion, 32, opened fire at an Interna...",5,7,12,Other,32,Yes,He was diagnosed with paranoid schizophrenia a...,Yes,Purchased from an individual,"Two rifles (both assault), one revolver","AK-47 Norinco Arms variant, AK-47 Romarm Cugir...",Latino,Male,39.1637984,-119.7674034,Mass,2011
117,Connecticut Lottery shooting,"Newington, Connecticut",06-03-1998,"Lottery worker Matthew Beck, 35, gunned down f...",5,1,6,Workplace,35,Yes,He had been hospitalized for psychiatric reaso...,Yes,Unknown,One semiautomatic handgun,9mm semiautomatic handgun,white,Male,41.6856325,-72.72983827,Mass,1998
0,Nashville religious school shooting,"Nashville, TN",3-27-23,"Audrey Hale, 28, who was a former student at t...",6,1,6,School,28,-,-,-,-,"semiautomatic rifle, semiautomatic handgun",-,-,"F (identified as transgender, per police)",-,-,Mass,2023
107,Lockheed Martin shooting,"Meridian, Mississippi",08-07-2003,"Assembly line worker Douglas Williams, 48, ope...",7,8,15,Workplace,48,Yes,"His cousin said he was depressed and ""going th...",Yes,Purchased from an individual,"One semiautomatic handgun, two rifles, one der...",.45-caliber Ruger P90 semiautomatic handgun; ....,white,Male,32.410842,-88.634539,Mass,2003
48,Walmart shooting in suburban Denver,"Thornton, Colorado",11-1-17,"Scott Allen Ostrem, 47, walked into a Walmart ...",3,0,3,Other,47,Unclear,-,TBD,-,semiautomatic handgun,-,White,M,39.876374,-104.986132,Mass,2017
115,Thurston High School shooting,"Springfield, Oregon",21-05-1998,After he was expelled for having a gun in his ...,4,25,29,School,15,Yes,Doctors testified that he was a paranoid schiz...,No,"Purchased variously from friend and father, an...","Two semiautomatic handguns, one rifle","9mm Glock, .22-caliber Ruger semiautomatic han...",white,Male,44.0462362,-123.0220289,Mass,1998

Total number of rows in df: 141

## firearms around the world, https://worldpopulationreview.com/country-rankings/gun-ownership-by-country

In [13]:
# Read the JSON data
df = pd.read_json('/Users/a/Desktop/ClassFolder_040123/final_project/gun-ownership-by-country-2023.json')

# Display the first few rows of the DataFrame
display(df.sample(30))
print("\nTotal number of rows in df:", df.shape[0])

                 country   firearms  per100   military     lawEnf
72                Latvia     205000    10.5    27936.0    17000.0
176               Tuvalu        100     1.2        NaN       26.0
96    Dominican Republic     795000     7.4   106495.0    46000.0
166              Bolivia     218000     2.0    87590.0    42000.0
116              Grenada       5000     4.6        NaN     1000.0
212          Timor-Leste       3000     0.3     2527.0     4000.0
61     Equatorial Guinea     112000    12.5     2760.0     2000.0
17                 Malta     119000    28.3     5547.0     1637.0
123             Botswana      97000     4.1    17100.0    11000.0
183         Burkina Faso     175000     0.9    43780.0    43000.0
209               Malawi      47000     0.3    24480.0     8400.0
186               Uganda     331000     0.8   116660.0    54000.0
0          United States  393347000   120.5  4535380.0  1016000.0
92                 Tonga       9000     8.0        NaN      200.0
88                Brazil   17510000     8.3  1316300.0   803000.0
189             Kiribati        900     0.8        NaN      200.0
203           Uzbekistan     127000     0.4   268400.0   150000.0
108  Antigua and Barbuda       5000     5.4      438.0      800.0
59           Afghanistan    4270000    12.5   331170.0   239000.0
86          Saint Martin       3000     8.5        NaN      100.0
7                Uruguay    1198000    34.7    62130.0    30000.0
29                Monaco       7000    19.6        NaN     1000.0
163                 Peru     633000     2.0   473400.0   142000.0
21              Pakistan   43917000    22.3  2315480.0   944000.0
68                  Guam      20000    11.5        NaN      500.0
40                 Qatar     390000    16.7    30680.0     5000.0
50            San Marino       5000    14.4        NaN      160.0
65             Guatemala    2062000    12.1   160600.0    43000.0
154               Poland     968000     2.5   307200.0   188000.0
14       North Macedonia     621000    29.8    29530.0    21000.0

Total number of rows in df: 217

## https://www.theviolenceproject.org/

In [14]:
# load excel file
xls = pd.ExcelFile('/Users/a/Desktop/ClassFolder_040123/final_project/Violence Project Mass Shooter Database - Version 6.1.xlsx')

# read all sheets to a dictionary
data = pd.read_excel(xls, sheet_name=None, header=1)

# data is now a dictionary where each key-value pair corresponds to a sheet
# you can access each DataFrame like so:
full_database_df = data['Full Database']


# display the various dfs
print("\nTotal number of rows in full_database_df:", full_database_df.shape[0])
display(full_database_df.sample(20))

Total number of rows in full_database_df: 189

,Case #,Shooter Last Name,Shooter First Name,Full Date,Day of Week,Day,Month,Year,Street Number,Street Name,City,State,County,Zip Code,Latitude,Longitude,State Code,Region,Urban/Suburban/Rural,Metro/Micro Statistical Area Type,Location,Insider or Outsider,Workplace Shooting,Multiple Locations,Other Location,...,Motive: Unknown,Role of Psychosis in the Shooting,Social Media Use,Leakage,Leakage How,Leakage Who,Leakage Specific/Nonspecific,Interest in Past Mass Violence,Relationship with Other Shooting(s),Specify Relationship to Other Shooting(s),Legacy Token,Pop Culture Connection,Specify Pop Culture Connection,Planning,Performance,Interest in Firearms,Firearm Proficiency,Total Firearms Brought to the Scene,Other Weapons or Gear,Specify Other Weapons or Gear,On-Scene Outcome,Who Killed Shooter On Scene,Attempt to Flee,Insanity Defense,Criminal Sentence
188,190,Bing,Andre,11/22/2022,Tuesday,22,11,2022,1521,Sam's Cir,Chesapeake,VA,City of Chesapeake,23320,36.772622,-76.251284,46,0,0,metropolitan,4,1,1,0,NaN,...,1.0,2.0,0.0,0.0,NaN,NaN,0,0.0,1.0,Two days after Club Q shooting,1.0,0.0,NaN,1.0,0.0,0.0,NaN,1.0,1.0,Several additional magazines,0.0,1.0,0.0,2.0,0.0
147,149,Cetin,Arcan,9/23/2016,Friday,23,9,2016,201,Cascade Mall Dr,Burlington,WA,Skagit County,98233,48.464723,-122.337055,47,3,1,metropolitan,4,0,0,0,NaN,...,1.0,0.0,1.0,0.0,NaN,NaN,NaN,1.0,1.0,Initially tried to emulate James Holmes by sho...,0.0,0.0,NaN,0.0,0.0,1.0,1.0,1.0,0.0,NaN,3.0,0.0,0.0,2.0,0.0
5,6,White,Joseph,9/23/1970,Wednesday,23,9,1970,Building 12,W. Averell Harriman State Office Campus,Albany,NY,Albany County,12240,42.614852,-73.970812,32,2,0,metropolitan,6,1,1,0,NaN,...,1.0,0.0,2.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,1.0,0.0,NaN,0.0,0.0,0.0,2.0,1.0,0.0,NaN,0.0,1.0,0.0,2.0,0.0
7,8,Grace,Edwin,6/21/1972,Wednesday,21,6,1972,383,Kings Hwy,Cherry Hill,NJ,Camden County,8034,39.927991,-74.994341,30,2,1,metropolitan,6,1,1,0,NaN,...,0.0,0.0,2.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,3.0,2.0,0.0,NaN,0.0,1.0,0.0,2.0,0.0
170,172,Anderson,David,12/10/2019,Tuesday,10,12,2019,223,Martin Luther King Jr Dr,Jersey City,NJ,Hudson County,7305,40.707135,-74.083691,30,2,0,metropolitan,4,0,0,1,8,...,0.0,0.0,1.0,0.0,NaN,NaN,NaN,1.0,0.0,NaN,1.0,0.0,NaN,1.0,0.0,0.0,3.0,5.0,1.0,"Pipe bomb, homemade silencer, homemade device ...",1.0,2.0,0.0,2.0,0.0
141,142,Farook,Syed Rizwan,12/2/2015,Wednesday,2,12,2015,1365,S Waterman Ave,San Bernardino,CA,San Bernardino County,92408,34.075766,-117.277467,5,3,0,metropolitan,6,1,1,1,8,...,0.0,0.0,1.0,0.0,NaN,NaN,NaN,1.0,0.0,NaN,1.0,0.0,NaN,1.0,0.0,0.0,2.0,4.0,1.0,"load-bearing vest, bombs",1.0,2.0,0.0,2.0,0.0
64,65,Torres,Arturo,12/18/1997,Thursday,18,12,1997,1808,N Batavia St,Orange,CA,Orange County,92865,33.817491,-117.862546,5,3,1,metropolitan,9,1,1,0,NaN,...,0.0,0.0,2.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,3.0,3.0,0.0,NaN,1.0,2.0,0.0,2.0,0.0
146,148,Johnson,Micah,7/7/2016,Thursday,7,7,2016,801,Main St,Dallas,TX,Dallas County,75202,32.779742,-96.805298,43,0,0,metropolitan,8,0,0,0,NaN,...,0.0,0.0,1.0,1.0,4,9,0,1.0,0.0,NaN,0.0,2.0,His Facebook had a photo with a member of the ...,1.0,0.0,1.0,3.0,3.0,1.0,"bombs, bulletproof vests at home",1.0,2.0,0.0,2.0,0.0
89,90,Brown,Elijah,7/2/2004,Friday,2,7,2004,4612,Speaker Rd,Kansas City,KS,Wyandotte County,66106,39.096158,-94.684427,16,1,0,metropolitan,9,1,1,0,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,2.0,0.0,NaN,0.0,1.0,0.0,2.0,0.0
66,67,Golden,Andrew,3/24/1998,Tuesday,24,3,1998,1800,Highway 91 W,Jonesboro,AR,Craighead County,72404,35.857012,-90.805986,4,0,2,metropolitan,0,1,0,0,NaN,...,0.0,0.0,2.0,1.0,0,6,1,0.0,0.0,NaN,0.0,0.0,NaN,1.0,0.0,1.0,3.0,10.0,1.0,"crossbow, machete, military belt, knives",2.0,0.0,1.0,1.0,5.0
32,33,Cruse,William,4/23/1987,Thursday,23,4,1987,4711,NE Babcock St,Palm Bay,FL,Brevard County,32905,28.032451,-80.620433,9,0,1,metropolitan,4,0,0,1,7,...,0.0,1.0,2.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,1.0,1.0,3.0,0.0,NaN,2.0,0.0,1.0,1.0,1.0
165,167,Martin,Gary,2/15/2019,Friday,15,2,2019,401,S Highland Ave,Aurora,IL,Kane County,60506,41.753845,-88.331270,13,1,0,metropolitan,9,1,1,0,NaN,...,0.0,0.0,0.0,1.0,0,4,1,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,1.0,1.0,0.0,NaN,1.0,2.0,0.0,2.0,0.0
116,117,Thornton,Omar,8/3/2010,Tuesday,3,8,2010,131,Chapel Rd,Manchester,CT,Hartford County,6042,41.797974,-72.569984,7,2,1,metropolitan,9,1,1,0,NaN,...,0.0,0.0,1.0,1.0,0,1,1,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,1.0,3.0,0.0,NaN,0.0,1.0,0.0,2.0,0.0
95,96,Cranshaw,Freddy,8/28/2005,Sunday,28,8,2005,11330,FM-100,Honey Grove,TX,Fannin County,75446,33.742416,-95.911382,43,0,2,micropolitan,3,0,0,1,8,...,0.0,1.0,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,1.0,2.0,0.0,NaN,0.0,1.0,0.0,2.0,0.0
34,35,Hayes,Michael,7/17/1988,Sunday,17,7,1988,3336,Old Salisbury Rd,Winston Salem,NC,Forsyth County,27127,35.999209,-80.274421,33,0,2,metropolitan,8,0,0,0,NaN,...,0.0,3.0,2.0,1.0,0,3,1,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,0.0,NaN,2.0,0.0,0.0,1.0,4.0
10,11,Allaway,Edward,7/12/1976,Monday,12,7,1976,800,N State College Blvd,Fullerton,CA,Orange County,92831,33.879942,-117.885447,5,3,0,metropolitan,1,1,1,0,NaN,...,0.0,3.0,2.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,3.0,1.0,0.0,NaN,2.0,0.0,0.0,1.0,4.0
35,36,Henderson,Clemmie,9/22/1988,Thursday,22,9,1988,1310,S Ashland Ave,Chicago,IL,Cook County,60608,41.864636,-87.667065,13,1,0,metropolitan,4,0,0,1,0,...,1.0,1.0,2.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,3.0,1.0,0.0,NaN,1.0,2.0,0.0,2.0,0.0
18,19,Moore,Lawrence,5/7/1981,Thursday,7,5,1981,NaN,Front St NE,Salem,OR,Marion County,97301,44.960783,-123.034276,37,3,0,metropolitan,5,0,0,0,NaN,...,0.0,2.0,2.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,0.0,NaN,2.0,0.0,0.0,1.0,3.0
126,127,Page,Wade,8/5/2012,Sunday,5,8,2012,7512,S Howell Ave,Oak Creek,WI,Milwaukee County,53154,42.907980,-87.908477,49,1,1,metropolitan,3,0,0,0,NaN,...,0.0,0.0,1.0,0.0,0,5,0,1.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,0.0,3.0,1.0,0.0,NaN,0.0,1.0,0.0,2.0,0.0
162,164,Bowers,Robert,10/27/2018,Saturday,27,10,2018,5898,Wilkins Ave,Pittsburgh,PA,Allegheny County,15217,40.443580,-79.921239,38,2,0,metropolitan,3,0,0,0,NaN,...,0.0,0.0,1.0,1.0,4,9,0,1.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,1.0,1.0,5.0,0.0,NaN,2.0,0.0,1.0,3.0,NaN

In [15]:
# load excel file
xls = pd.ExcelFile('/Users/a/Desktop/ClassFolder_040123/final_project/Violence Project Mass Shooter Database - Version 6.1.xlsx')

# read all sheets to a dictionary
data = pd.read_excel(xls, sheet_name=None)

# data is now a dictionary where each key-value pair corresponds to a sheet
# you can access each DataFrame like so:
firearms_data_df = data['Firearms Data']
victims_df = data['Victims Data']
community_df = data['Community Data']
trends_df = data['Trend Data']


# display the various dfs
print("\nTotal number of rows in firearms_data_df:", firearms_data_df.shape[0])
display(firearms_data_df.sample(20))

print("\nTotal number of rows in victims_df:", victims_df.shape[0])
display(victims_df.sample(20))

print("\nTotal number of rows in community_df:", community_df.shape[0])
display(community_df.sample(20))

print("\nTotal number of rows in trends_df:", trends_df.shape[0])
display(trends_df.sample(20))

Total number of rows in firearms_data_df: 404

,Case #,Shooter Last Name,Shooter First Name,Full Date,Make and Model,Classification,Caliber,Used in Shooting?,Modified,Large Capacity Magazine,Extended Magazine,When Obtained,Legal Purchase,Illegal Purchase,Assembled with Legal Parts,Gifted,Theft,Unknown
354,161,Pagourtzis,Dimitrios,2018-05-18 00:00:00,.38-caliber Rossi revolver,0.0,2.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,1.0,0.0
225,109,Zamora,Isaac,2008-09-02 00:00:00,Winchester lever-action rifle,2.0,NaN,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,2.0,0.0
180,87,Williams,Doug,2003-07-08 00:00:00,12-gauge shotgun,1.0,2.0,1.0,0.0,0.0,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0
256,124,Goh,One,2012-04-02 00:00:00,.45-caliber pistol,0.0,2.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
116,59,Vernon,Michael,1995-12-19 00:00:00,9mm CZ Model 85 pistol,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0
302,144,Dalton,Jason,2016-02-20 00:00:00,9mm Glock 19 pistol,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
266,129,Lanza,Adam,2012-12-14 00:00:00,10mm Glock 20 pistol,0.0,2.0,2.0,0.0,1.0,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0
3,1,Whitman,Charles,1966-08-01 00:00:00,6.35mm Galesi-brescia pistol,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
356,163,Casarez,Javier,2018-09-12 00:00:00,.50-caliber Smith & Wesson 500 revolver,0.0,NaN,1.0,0.0,0.0,NaN,1.0,3.0,0.0,0.0,0.0,0.0,0.0
1,1,Whitman,Charles,1966-08-01 00:00:00,Remington .35-caliber Model 141 pump-action rifle,2.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
122,62,Drega,Carl,1997-08-19 00:00:00,.223-caliber Colt AR-15 rifle,3.0,2.0,1.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0
222,106,Kazmierczak,Steven,2008-02-14 00:00:00,.380-caliber Hi-Point CF380 pistol,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
98,49,Ferri,Gian,1993-07-01 00:00:00,.45-caliber Norinco Model 1911A1 pistol,0.0,2.0,2.0,0.0,0.0,0.0,NaN,0.0,3.0,0.0,0.0,0.0,0.0
361,164,Bowers,Robert,2018-10-27 00:00:00,Shotgun,1.0,2.0,0.0,0.0,0.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0
70,34,Farley,Richard,1988-02-16 00:00:00,Pump-action shotgun,1.0,2.0,NaN,0.0,0.0,NaN,1.0,3.0,0.0,0.0,0.0,0.0,0.0
183,87,Williams,Doug,2003-07-08 00:00:00,.45-caliber Ruger pistol,0.0,2.0,0.0,0.0,1.0,0.0,NaN,2.0,0.0,0.0,0.0,0.0,0.0
55,30,Crossley,Wayne,1984-07-24 00:00:00,.45-caliber Colt pistol,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
124,63,Wise,Hastings Arthur,1997-09-15 00:00:00,9mm pistol,0.0,1.0,1.0,0.0,0.0,0.0,NaN,0.0,5.0,0.0,0.0,0.0,0.0
205,100,Roberts,Charles,2006-10-02 00:00:00,12-gauge Browning shotgun,1.0,2.0,1.0,0.0,0.0,NaN,NaN,3.0,0.0,0.0,0.0,0.0,0.0
96,48,Drake III,Lynwood,1992-11-08 00:00:00,.32-caliber revolver,0.0,0.0,1.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,1.0

Total number of rows in victims_df: 1325

,Case #,Shooter Last Name,Shooter First Name,Full Date,Victim Name,Age,Gender,Race,Knew Shooter,"If Known, Relationship to Shooter",Relationship to Shooter,Life Expectancy,Years Lost
164,29,Huberty,James,7/18/1984,Neva Denise Caine,22.0,1.0,0.0,0.0,NaN,0.0,75.6,53.6
345,56,Ferguson,Rodriguez,12/31/1994,Jamie Hunter,39.0,0.0,NaN,0.0,NaN,0.0,66.6,27.6
761,126,Holmes,James,7/20/2012,Veronica Moser-Sullivan,6.0,1.0,0.0,0.0,NaN,0.0,80.7,74.7
1083,158,Cruz,Nikolas,2/14/2018,Alaina Petty,14.0,1.0,0.0,0.0,NaN,0.0,80.5,66.5
1159,168,Craddock,DeWayne,5/31/2019,Christopher Kelly Rapp,54.0,0.0,0.0,1.0,coworker,3.0,68.0,14
274,41,Hennard,George,10/16/1991,Nancy Faye Hedgepeth Stansbury,44.0,1.0,0.0,0.0,NaN,0.0,72.2,28.2
226,36,Henderson,Clemmie,9/22/1988,Irma C. Ruiz,40.0,1.0,2.0,0.0,NaN,0.0,71.1,31.1
1096,160,Reinking,Travis,4/22/2018,Taurean C. Sanderlin,29.0,0.0,1.0,0.0,NaN,0.0,64.5,35.5
679,113,Hasan,Nidal,11/5/2009,Jason Dean Hunt,22.0,0.0,0.0,2.0,stationed at Fort Hood,5.0,72.7,50.7
588,102,Cho,Seung-Hui,4/16/2007,Jeremy Michael Herbstritt,27.0,0.0,0.0,2.0,classmate,4.0,70.7,43.7
201,32,Sherrill,Patrick,8/20/1986,Leroy Orrin Phillips,42.0,0.0,NaN,1.0,coworker,3.0,65.6,23.6
1224,177,Long,Robert,3/16/2021,Suncha Kim,69.0,1.0,3.0,2.0,She worked at a business he frequented,5.0,71.1,2.1
298,46,Houston,Eric,5/1/1992,Beamon Hill,16.0,0.0,1.0,0.0,NaN,0.0,62.5,46.5
267,41,Hennard,George,10/16/1991,Zona Mae Hunnicutt Lynn,45.0,1.0,NaN,0.0,NaN,0.0,71.1,26.1
856,138,Roof,Dylann,6/17/2015,Daniel Lee Simmons Sr.,74.0,0.0,1.0,0.0,NaN,0.0,80.2,6.2
971,152,Vang,Nengmy,3/22/2017,Karen Barclay,62.0,1.0,0.0,1.0,Wifes coworker,5.0,74.1,12.1
1296,185,Ramos,Salvador,5/24/2022,Eva Mireles,44.0,1.0,2.0,0.0,NaN,0.0,76.6,32.6
180,29,Huberty,James,7/18/1984,Arisdelsi Vuelvas-Vargas,31.0,1.0,2.0,0.0,NaN,0.0,71.1,40.1
473,81,Park,Ki Yung,1/9/2001,Kathy Chang,23.0,1.0,3.0,1.0,business acquaintance,3.0,77.4,54.4
484,84,Ferguson,Joseph,9/8/2001,John Derek Glimstad,19.0,0.0,0.0,0.0,NaN,0.0,70.7,51.7

Total number of rows in community_df: 130

,Case #,Shooter Last Name,Shooter First Name,Location (Code),Location (Specify),Shooting Start Time,Shooting End Time,Time of Day,Zip Code,Total Population,Median Age,% White Alone,% Female Household,% Rental Units,% Employed,% High School Graduate,% College Graduate,% Without Health Insurance,Nearest Hospital (Miles),N Mental Health Providers in Zip Code,N Gun Stores in Zip Code,Size of Police Dept,Homicide Rate
64,123,Dekraai,Scott,4,Retail,13:21:00,13:26:00,1.0,90740,23729,57.5,83.2,6.1,25.2,94.4,42.3,12.6,NaN,5.8,1.0,0.0,36,4.10
63,122,Sencion,Eduardo,5,Restaurant / Bar / Nightclub,08:58:00,9:06,0.0,89701,27625,40.2,79.3,12.3,41.4,52.8,36.6,39.1,23.60,5.5,5.0,2.0,NaN,NaN
29,88,Tapia,Salvador,6,Workplace,08:37:00,NaN,0.0,60609,2896016,31.5,42.0,18.9,56.2,55.1,71.8,25.5,NaN,NaN,NaN,NaN,13400,22.04
110,171,Ator,Seth,8,Driving,15:17:00,17:30:00,1.0,79762,44014,31.0,95.5,14.9,43.3,68.5,84.3,22.7,18.50,3.7,1.0,2.0,170,9.70
26,85,Lockey,William,6,Workplace,08:00:00,NaN,0.0,46628,26726,34.0,63.7,18.3,30.2,62.9,79.3,18.4,NaN,3.8,1.0,0.0,255,19.37
86,147,Mateen,Omar,5,Restaurant / Bar / Nightclub,01:58:00,05:15:00,3.0,32806,26797,38.6,83.9,11.0,35.9,64.9,28.5,21.3,16.80,0.6,1.0,2.0,697,5.80
103,164,Bowers,Robert,3,House of Worship,09:54:00,11:08:00,0.0,15217,28049,34.5,80.2,4.4,48.5,62.3,96.7,72.1,3.70,NaN,3.0,0.0,1100,22.40
120,181,Cassidy,Samuel,6,Workplace,6:34,6:40,0.0,95110,19928,32.4,20.5,11.2,61.3,68.4,75.7,37.4,8.22,3.0,4.0,0.0,959,4.52
80,139,Abdulazeez,Muhammad,2,Military Site,10:45:00,11:15:00,0.0,37406,14627,35.3,16.6,34.5,53.7,43.5,43.4,2.0,13.80,4.9,1.0,0.0,477,15.50
14,73,Floyd,Zane,4,Retail,05:16:00,05:24:00,0.0,89119,49445,33.2,51.2,12.4,78.4,62.9,34.2,2.6,NaN,0.6,5.0,0.0,2353,12.80
68,127,Page,Wade,3,House of Worship,10:25:00,NaN,0.0,53154,34451,37.4,87.7,8.2,38.7,69.0,92.2,29.3,7.60,NaN,5.0,0.0,44,17.30
84,144,Dalton,Jason,5,Restaurant / Bar / Nightclub,18:00:00,00:45:00,2.0,49004,15828,38.2,82.3,12.0,21.9,59.8,91.4,29.0,9.30,3.5,0.0,0.0,257,7.90
54,113,Hasan,Nidal,6,Military Site,13:30:00,NaN,1.0,76544,29943,21.9,64.0,11.8,99.3,59.4,95.1,12.1,NaN,3.0,1.0,0.0,NaN,8.62
89,150,Santiago,Esteban,4,Airport,13:00:00,NaN,1.0,33315,14110,43.1,87.5,9.5,47.1,68.7,89.4,35.7,19.60,4.6,0.0,1.0,500,10.30
87,148,Johnson,Micah,8,City - Attack on Law Enforcement,20:59:00,02:30:00,3.0,75202,2236,30.8,68.9,3.3,83.0,87.2,100.0,72.4,8.10,2.0,2.0,0.0,2841,9.10
69,128,Engeldinger,Andrew,6,Workplace,16:30:00,NaN,1.0,55405,15411,31.1,69.6,12.6,64.3,59.4,85.0,27.9,NaN,3.3,3.0,0.0,800,8.30
119,180,Hole,Brandon Scott,6,Workplace,23:00,23:04,3.0,46241,31941,31.0,62.7,23.0,43.7,59.6,71.2,8.7,14.90,9.3,1.0,0.0,1700,10.60
113,174,Ferrill,Anthony,6,Workplace,13:45:00,16:30:00,1.0,53208,29669,31.4,35.8,23.5,63.0,44.3,84.4,26.6,23.20,1.9,2.0,0.0,1800,16.62
55,114,Clemmons,Maurice,5,Restaurant / Bar / Nightclub,08:15:00,02:45:00,0.0,98444,33956,30.1,53.4,18.4,59.7,57.4,31.2,5.0,20.30,2.6,1.0,1.0,78,8.10
22,81,Park,Ki Yung,4,Retail,12:00:00,12:00:00,1.0,77036,76146,28.3,37.2,16.9,81.1,58.5,64.9,21.1,NaN,1.9,5.0,2.0,4905,13.40

Total number of rows in trends_df: 85

,Year,U.S. Population (Census),Total U.S. Murders (FBI UCR),U.S. Murder Rate per Million,Mass Shootings (Incidents),Mass Shooting Rate Per Million,Mass Shooting Yearly Growth Rate (Incidents),Mass Shooting 3 Year Average (Incidents),Mass Shooting 5 Year Average (Incidents),Mass Shooting 10 Year Average (Incidents),Mass Shooting Deaths (Total),Deaths per Mass Shooting (Mean),Mass Shooting Death Rate per Million,Mass Shooting 3 Year Average (Deaths),Mass Shooting 5 Year Average (Deaths),Mass Shooting 10 Year Average (Deaths)
74,NaN,NaN,NaN,NaN,11,"Austin, TX. Aug. 1, 1966",15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1969,202676946,14760,72.825254,1,0.004934,2.18,1.000000,NaN,NaN,4.0,4.000000,0.019736,5.666667,NaN,NaN
76,NaN,NaN,NaN,NaN,13,"Edmond, OK. Aug. 20, 1986",14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,21,"Virginia Beach, VA. May 31, 2019",12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1978,222584545,19560,87.876721,1,0.004493,2.83,1.666667,1.50,1.375,5.0,5.000000,0.022463,9.666667,8.50,7.375000
1,1967,198712056,12240,61.596665,1,0.005032,2.06,NaN,NaN,NaN,6.0,6.000000,0.030194,NaN,NaN,NaN
24,1990,249464396,23440,93.961304,1,0.004009,4,2.000000,1.60,2.1,11.0,11.000000,0.044094,13.333333,12.00,14.700000
50,2016,323071342,17413,53.898312,5,0.015476,8.49,4.333333,4.80,4.7,70.0,14.000000,0.216670,42.333333,44.20,38.800000
36,2002,287973924,16229,56.355797,1,0.003473,5.67,2.666667,3.60,3.5,4.0,4.000000,0.013890,12.666667,20.60,18.200000
71,NaN,Total,185,NaN,8,"Uvalde, TX, May 24, 2022",21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,14,"Fort Hood, TX. Nov. 5, 2009",13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,15,"Littleton, CO. Apr. 20, 1999",13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,12,"San Bernardino, CA. Dec. 2, 2015",14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1980,227224681,23040,101.397436,3,0.013203,3,2.000000,2.00,1.714286,14.0,4.666667,0.061613,9.500000,10.75,9.285714
81,NaN,NaN,NaN,NaN,18,"Thousand Oaks, CA. Nov. 8, 2018",12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1986,240132887,20613,85.839971,1,0.004164,3.57,2.000000,2.40,2.333333,14.0,14.000000,0.058301,19.333333,18.40,15.222222
43,2009,307006550,15399,50.158539,5,0.016286,6.94,4.666667,4.40,3.7,42.0,8.400000,0.136805,39.000000,32.80,23.800000
15,1981,229465714,22520,98.141023,2,0.008716,3.09,2.500000,2.25,1.75,9.0,4.500000,0.039222,11.500000,11.25,9.250000
34,2000,281421906,15586,55.383038,3,0.01066,5.35,4.333333,3.80,3.9,17.0,5.666667,0.060408,27.333333,21.60,21.900000
64,NaN,1960s,5,2.702703,1,"Las Vegas, NV. Oct. 1, 2017",60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN