In [11]:
import pandas as pd

In [12]:
# Read the main file
mass_shooting = pd.read_csv('../Resources/mass_shooting_1982to2023_cleaned.csv')
set(mass_shooting['state'].to_list())

{' Alabama',
 ' Arizona',
 ' Arkansas',
 ' California',
 ' Colorado',
 ' Connecticut',
 ' D.C.',
 ' Florida',
 ' Georgia',
 ' Hawaii',
 ' Illinois',
 ' Indiana',
 ' Iowa',
 ' Kansas',
 ' Kentucky',
 ' Lousiana',
 ' Maryland',
 ' Massachusetts',
 ' Michigan',
 ' Minnesota',
 ' Mississippi',
 ' Missouri',
 ' Nebraska',
 ' Nevada',
 ' New Jersey',
 ' New York',
 ' North Carolina',
 ' Ohio',
 ' Oklahoma',
 ' Oregon',
 ' Pennsylvania',
 ' South Carolina',
 ' Tennessee',
 ' Texas',
 ' Utah',
 ' Virginia',
 ' Washington',
 ' Wisconsin'}

In [13]:
# need to clean trailing spaces from state
mass_shooting['state'] = mass_shooting['state'].str.strip() 
mass_shooting

,case,date,year,month,city,state,fatalities,injured,total_victims,location_catg,type,age_of_shooter,race,latitude,longitude
0,Nashville religious school shooting,2023-03-27,2023,March,Nashville,Tennessee,6,1,6,School,Mass,28.0,Unknown,36.162663,-86.781601
1,Michigan State University shooting,2023-02-13,2023,February,East Lansing,Michigan,3,5,8,School,Mass,43.0,Black,42.746880,-84.483704
2,Half Moon Bay spree shooting,2023-01-23,2023,January,Half Moon Bay,California,7,1,8,Workplace,Spree,67.0,Asian,37.463551,-122.428589
3,LA dance studio mass shooting,2023-01-21,2023,January,Monterey Park,California,11,10,21,Other,Mass,72.0,Asian,34.059818,-118.122803
4,Virginia Walmart shooting,2022-11-22,2022,November,Chesapeake,Virginia,6,6,12,Workplace,Mass,31.0,Black,36.714588,-76.249931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Shopping centers spree killings,1987-04-23,1987,April,Palm Bay,Florida,6,14,20,Other,Spree,59.0,White,28.033189,-80.642969
137,United States Postal Service shooting,1986-08-20,1986,August,Edmond,Oklahoma,15,6,21,Workplace,Mass,44.0,White,35.667202,-97.429370
138,San Ysidro McDonald's massacre,1984-07-18,1984,July,San Ysidro,California,22,19,41,Other,Mass,41.0,White,32.552001,-117.043081
139,Dallas nightclub shooting,1984-06-29,1984,June,Dallas,Texas,6,1,7,Other,Mass,39.0,White,32.925166,-96.838676
140,Welding shop shooting,1982-08-20,1982,August,Miami,Florida,8,3,11,Other,Mass,51.0,White,25.796491,-80.226683

In [14]:
# Read the gun laws file
gun_laws = pd.read_csv('../Resources/gun_laws_1991to2019_cleaned.csv')
gun_laws

,STATE,YEAR,dealer_regulations,buyer_regulations,gun_posses_prohibitions,background_checks,ammunition_regulations,possession_regulations,concealed_carry_permits,assault_weapons_bans,child_access_prevention,gun_trafficking,domestic_violence,no_preemption,no_stand_your_ground,immunity,total_laws
0,Alabama,1991,7,1,1,0,0,0,3,0,0,0,0,1,1,1,15
1,Alaska,1991,0,0,1,0,0,1,6,0,0,0,0,0,1,1,10
2,Arizona,1991,0,0,3,0,0,1,6,0,0,0,0,0,1,1,12
3,Arkansas,1991,0,0,3,0,0,1,6,0,0,0,0,3,1,1,15
4,California,1991,12,5,7,11,0,5,5,4,4,0,2,2,1,0,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1445,Virginia,2019,0,0,4,0,0,1,4,0,0,2,1,0,1,0,13
1446,Washington,2019,7,4,4,11,1,4,5,0,5,0,7,0,1,0,49
1447,West Virginia,2019,1,2,6,0,2,0,0,0,0,0,7,0,0,0,18
1448,Wisconsin,2019,0,1,5,0,0,2,5,0,2,0,6,0,1,1,23
1449,Wyoming,2019,0,0,1,0,0,3,0,0,0,0,0,0,0,1,5

In [15]:
# Merge the mass shooting file with the gun laws file based on 'year' and 'state'
merged_file = pd.merge(mass_shooting, gun_laws, left_on=['year', 'state'], right_on=['YEAR', 'STATE'], how='left')
merged_file

,case,date,year,month,city,state,fatalities,injured,total_victims,location_catg,...,possession_regulations,concealed_carry_permits,assault_weapons_bans,child_access_prevention,gun_trafficking,domestic_violence,no_preemption,no_stand_your_ground,immunity,total_laws
0,Nashville religious school shooting,2023-03-27,2023,March,Nashville,Tennessee,6,1,6,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Michigan State University shooting,2023-02-13,2023,February,East Lansing,Michigan,3,5,8,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Half Moon Bay spree shooting,2023-01-23,2023,January,Half Moon Bay,California,7,1,8,Workplace,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LA dance studio mass shooting,2023-01-21,2023,January,Monterey Park,California,11,10,21,Other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Virginia Walmart shooting,2022-11-22,2022,November,Chesapeake,Virginia,6,6,12,Workplace,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Shopping centers spree killings,1987-04-23,1987,April,Palm Bay,Florida,6,14,20,Other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,United States Postal Service shooting,1986-08-20,1986,August,Edmond,Oklahoma,15,6,21,Workplace,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,San Ysidro McDonald's massacre,1984-07-18,1984,July,San Ysidro,California,22,19,41,Other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,Dallas nightclub shooting,1984-06-29,1984,June,Dallas,Texas,6,1,7,Other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,Welding shop shooting,1982-08-20,1982,August,Miami,Florida,8,3,11,Other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Read the demographics file
demographics = pd.read_csv('../Resources/us_demogrpahics_2009to2020_cleaned.csv', encoding="utf-8")
demographics

,Year,State,Total Population,Poverty,Median Age,Unemployed Civilians,Median Household Income,Per Capita Income,% in Poverty,% in Unemployed
0,2009,Alabama,4633360.0,757833.0,37.2,0.0,41216.0,22732.0,16.36,0.00
1,2009,Alaska,683142.0,64038.0,32.7,0.0,64635.0,29382.0,9.37,0.00
2,2009,Arizona,6324865.0,914040.0,34.8,0.0,50296.0,25203.0,14.45,0.00
3,2009,Arkansas,2838143.0,488788.0,36.9,0.0,38542.0,20977.0,17.22,0.00
4,2009,California,36308527.0,4694423.0,34.6,0.0,60392.0,29020.0,12.93,0.00
...,...,...,...,...,...,...,...,...,...,...
595,2020,Virginia,8509358.0,826708.0,38.4,202745.0,76398.0,41255.0,9.72,2.38
596,2020,Washington,7512465.0,751044.0,37.8,188562.0,77006.0,40837.0,10.00,2.51
597,2020,West Virginia,1807426.0,300152.0,42.7,52031.0,48037.0,27346.0,16.61,2.88
598,2020,Wisconsin,5806975.0,620947.0,39.6,109854.0,63293.0,34450.0,10.69,1.89
599,2020,Wyoming,581348.0,61006.0,38.0,13222.0,65304.0,34415.0,10.49,2.27

In [17]:
# Merge the merged file with the demographics file based on 'year' and 'state'
merged_file = pd.merge(merged_file, demographics, left_on=['year', 'state'], right_on=['Year', 'State'], how='left')
merged_file

,case,date,year,month,city,state,fatalities,injured,total_victims,location_catg,...,Year,State,Total Population,Poverty,Median Age,Unemployed Civilians,Median Household Income,Per Capita Income,% in Poverty,% in Unemployed
0,Nashville religious school shooting,2023-03-27,2023,March,Nashville,Tennessee,6,1,6,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Michigan State University shooting,2023-02-13,2023,February,East Lansing,Michigan,3,5,8,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Half Moon Bay spree shooting,2023-01-23,2023,January,Half Moon Bay,California,7,1,8,Workplace,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LA dance studio mass shooting,2023-01-21,2023,January,Monterey Park,California,11,10,21,Other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Virginia Walmart shooting,2022-11-22,2022,November,Chesapeake,Virginia,6,6,12,Workplace,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Shopping centers spree killings,1987-04-23,1987,April,Palm Bay,Florida,6,14,20,Other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,United States Postal Service shooting,1986-08-20,1986,August,Edmond,Oklahoma,15,6,21,Workplace,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,San Ysidro McDonald's massacre,1984-07-18,1984,July,San Ysidro,California,22,19,41,Other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,Dallas nightclub shooting,1984-06-29,1984,June,Dallas,Texas,6,1,7,Other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,Welding shop shooting,1982-08-20,1982,August,Miami,Florida,8,3,11,Other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
merged_file.columns

Index(['case', 'date', 'year', 'month', 'city', 'state', 'fatalities',
       'injured', 'total_victims', 'location_catg', 'type', 'age_of_shooter',
       'race', 'latitude', 'longitude', 'STATE', 'YEAR', 'dealer_regulations',
       'buyer_regulations', 'gun_posses_prohibitions', 'background_checks',
       'ammunition_regulations', 'possession_regulations',
       'concealed_carry_permits', 'assault_weapons_bans',
       'child_access_prevention', 'gun_trafficking', 'domestic_violence',
       'no_preemption', 'no_stand_your_ground', 'immunity', 'total_laws',
       'Year', 'State', 'Total Population', 'Poverty', 'Median Age',
       'Unemployed Civilians', 'Median Household Income', 'Per Capita Income',
       '% in Poverty', '% in Unemployed'],
      dtype='object')

In [19]:
# Save the merged file to a new CSV file
merged_file.to_csv('..\Resources\mass_shootings_merged_data.csv', index=False)