# Gun Violence in the US: Data Cleaning

In [1]:
# import dependencies
import pandas as pd

In [2]:
# read tSV file (tab separated)
file_path = "../Resources/gun-violence-data_01-2013_03-2018.csv"
df = pd.read_csv(file_path, encoding="utf-8")
df.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Julian Sims,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Bernard Gillis,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,...,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,0::Damien Bell||1::Desmen Noble||2::Herman Sea...,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,False,...,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,0::Stacie Philbrook||1::Christopher Ratliffe||...,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,False,...,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,0::Danielle Imani Jameison||1::Maurice Eugene ...,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0

In [3]:
# Getting list of column names 
df.columns.to_list()

['incident_id',
 'date',
 'state',
 'city_or_county',
 'address',
 'n_killed',
 'n_injured',
 'incident_url',
 'source_url',
 'incident_url_fields_missing',
 'congressional_district',
 'gun_stolen',
 'gun_type',
 'incident_characteristics',
 'latitude',
 'location_description',
 'longitude',
 'n_guns_involved',
 'notes',
 'participant_age',
 'participant_age_group',
 'participant_gender',
 'participant_name',
 'participant_relationship',
 'participant_status',
 'participant_type',
 'sources',
 'state_house_district',
 'state_senate_district']

In [4]:
# dropping unimportant variables
cols_to_drop = ['city_or_county', 'address', 'incident_url', 'source_url', 'incident_url_fields_missing',
               'congressional_district', 'gun_stolen',  'gun_type', 'location_description', 'n_guns_involved','notes',
               'participant_name', 'participant_relationship', 'participant_status', 'participant_type', 'sources',
               'state_house_district', 'state_senate_district', 'participant_age', 
                'participant_age_group', 'participant_gender']
df.drop(columns=cols_to_drop, inplace=True)
df.head()

,incident_id,date,state,n_killed,n_injured,incident_characteristics,latitude,longitude
0,461105,2013-01-01,Pennsylvania,0,4,Shot - Wounded/Injured||Mass Shooting (4+ vict...,40.3467,-79.8559
1,460726,2013-01-01,California,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",33.9090,-118.3330
2,478855,2013-01-01,Ohio,1,3,"Shot - Wounded/Injured||Shot - Dead (murder, a...",41.4455,-82.1377
3,478925,2013-01-05,Colorado,4,0,"Shot - Dead (murder, accidental, suicide)||Off...",39.6518,-104.8020
4,478959,2013-01-07,North Carolina,2,2,"Shot - Wounded/Injured||Shot - Dead (murder, a...",36.1140,-79.9569

### Processing the 'incident_characteristics' column

In [5]:
# Removing unwanted text
df['incident_characteristics'] = df['incident_characteristics'].str.replace(r'\(s\)', '', regex=True) 
df['incident_characteristics'] = df['incident_characteristics'].str.replace(r'\(.*?\)', '', regex=True)
df['incident_characteristics'] = df['incident_characteristics'].str.replace(r'\|\|', ',', regex=True)
df['incident_characteristics'] = df['incident_characteristics'].str.replace(r'\|', ',', regex=True) 
df['incident_characteristics'] = df['incident_characteristics'].str.replace('^', '') 

df.head()

,incident_id,date,state,n_killed,n_injured,incident_characteristics,latitude,longitude
0,461105,2013-01-01,Pennsylvania,0,4,"Shot - Wounded/Injured,Mass Shooting ,Possessi...",40.3467,-79.8559
1,460726,2013-01-01,California,1,3,"Shot - Wounded/Injured,Shot - Dead ,Mass Shoot...",33.9090,-118.3330
2,478855,2013-01-01,Ohio,1,3,"Shot - Wounded/Injured,Shot - Dead ,Shots Fire...",41.4455,-82.1377
3,478925,2013-01-05,Colorado,4,0,"Shot - Dead ,Officer Involved Incident,Officer...",39.6518,-104.8020
4,478959,2013-01-07,North Carolina,2,2,"Shot - Wounded/Injured,Shot - Dead ,Suicide,Mu...",36.1140,-79.9569

In [6]:
# Splitting the 'incident_characteristics' column 
df_split = df['incident_characteristics'].str.split(',', expand=True).fillna('0')
df_split.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,Shot - Wounded/Injured,Mass Shooting,Possession,Possession of gun by felon or prohibited person,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Shot - Wounded/Injured,Shot - Dead,Mass Shooting,Gang involvement,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Shot - Wounded/Injured,Shot - Dead,Shots Fired - No Injuries,Bar/club incident - in or around establishment,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Shot - Dead,Officer Involved Incident,Officer Involved Shooting - subject/suspect/pe...,Drug involvement,Kidnapping/abductions/hostage,Under the influence of alcohol or drugs,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Shot - Wounded/Injured,Shot - Dead,Suicide,Murder/Suicide,Attempted Murder/Suicide,Domestic Violence,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
# Checking values in columns
for i in range(0,20):
    print(f'Column #{i}')
    print('-' * 30)        
    print(df_split[i].value_counts())
    print('~' * 50)

Column #0
------------------------------
Shot - Wounded/Injured                                           93926
Shot - Dead                                                      45054
Non-Shooting Incident                                            41541
Shots Fired - No Injuries                                        33949
Armed robbery with injury/death and/or evidence of DGU found      7528
Institution/Group/Business                                        4316
TSA Action                                                        2653
Brandishing/flourishing/open carry/lost/found                     1350
Home Invasion                                                     1323
Possession                                                        1310
Drug involvement                                                  1005
Shots fired                                                        961
Gun stolen from owner                                              834
Officer Involved Incident                                          692
ATF/LE Confiscation/Raid/Arrest                                    450
Car-jacking                                                        389
0                                                                  326
Animal shot/killed                                                 309
Domestic Violence                                                  234
Accidental Shooting                                                229
Gang involvement                                                   177
School Incident                                                    118
Sex crime involving firearm                                        103
Kidnapping/abductions/hostage                                       95
Drive-by                                                            89
Implied Weapon                                                      88
Pistol-whipping                                                     87
Suicide - Attempt                                                   77
Possession of gun by felon or prohibited person                     63
Gun buy back action                                                 58
Non-Aggression Incident                                             51
Defensive Use                                                       50
Suicide                                                             34
Criminal act with stolen gun                                        30
Road rage                                                           28
Gun at school                                                       25
Murder/Suicide                                                      24
Bar/club incident - in or around establishment                      23
LOCKDOWN/ALERT ONLY: No GV Incident Occurred Onsite                 13
Guns stolen from law enforcement                                    10
Stolen/Illegally owned gun{s} recovered during arrest/warrant        8
Attempted Murder/Suicide                                             7
Under the influence of alcohol or drugs                              6
BB/Pellet/Replica gun                                                6
Gun shop robbery or burglary                                         5
ShotSpotter                                                          5
Child Involved Incident                                              4
Spree Shooting                                                       4
Hate crime                                                           4
House party                                                          3
Mass Shooting                                                        1
Unlawful purchase/sale                                               1
Gun range/gun shop/gun show shooting                                 1
Name: 0, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #1
------------------------------
0                                                                  96995
Officer Involved Incident                                          13881
Drive-by                                                           11873
Drug involvement                                                   11716
Home Invasion                                                       8664
                                                                   ...
Officer Involved Shooting - subject/suspect/perpetrator unarmed        1
Police Targeted                                                        1
Defensive Use - Crime occurs                                           1
School Shooting - elementary/secondary school                          1
Cleaning gun                                                           1
Name: 1, Length: 92, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #2
------------------------------
0                                                151892
Possession                                         9560
ATF/LE Confiscation/Raid/Arrest                    7543
Brandishing/flourishing/open carry/lost/found      4453
Home Invasion - No death or injury                 4152
                                                  ...
Terrorism Involvement                                 3
Child injured self                                    3
 no injury/death                                      2
 victim shoots subject/suspect/perpetrator            1
NAV                                                   1
Name: 2, Length: 114, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #3
------------------------------
0                                                  184639
Possession                                           8733
Possession of gun by felon or prohibited person      4241
Accidental/Negligent Discharge                       3617
Brandishing/flourishing/open carry/lost/found        3514
                                                    ...
Non-Aggression Incident                                 4
Child injured self                                      3
Shots Fired - No Injuries                               3
Political Violence                                      1
Suicide                                                 1
Name: 3, Length: 111, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #4
------------------------------
0                                                                208283
Possession of gun by felon or prohibited person                    3996
Possession                                                         2525
Brandishing/flourishing/open carry/lost/found                      2189
Stolen/Illegally owned gun{s} recovered during arrest/warrant      1914
                                                                  ...
Accidental Shooting                                                   2
Political Violence                                                    2
Murder/Suicide                                                        2
TSA Action                                                            2
Gun buy back action                                                   1
Name: 4, Length: 107, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #5
------------------------------
0                                                                222651
Stolen/Illegally owned gun{s} recovered during arrest/warrant      1536
Brandishing/flourishing/open carry/lost/found                      1503
Possession of gun by felon or prohibited person                    1401
Possession                                                         1222
                                                                  ...
Attempted Murder/Suicide                                              2
Hate crime                                                            2
Accidental Shooting - Death                                           1
Political Violence                                                    1
NAV                                                                   1
Name: 5, Length: 103, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #6
------------------------------
0                                                                230774
Possession                                                          888
Brandishing/flourishing/open carry/lost/found                       875
Stolen/Illegally owned gun{s} recovered during arrest/warrant       816
Possession of gun by felon or prohibited person                     662
                                                                  ...
Accidental Shooting - Injury                                          1
Institution/Group/Business                                            1
ShotSpotter                                                           1
Home Invasion - No death or injury                                    1
TSA Action                                                            1
Name: 6, Length: 98, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #7
------------------------------
0                                                                235235
Brandishing/flourishing/open carry/lost/found                       505
Stolen/Illegally owned gun{s} recovered during arrest/warrant       410
Possession of gun by felon or prohibited person                     409
Possession                                                          361
                                                                  ...
Accidental Shooting at a Business                                     1
Home Invasion - Resident injured                                      1
Ghost gun                                                             1
Gun shop robbery or burglary                                          1
Mass Murder                                                           1
Name: 7, Length: 92, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #8
------------------------------
0                                                                                237615
Brandishing/flourishing/open carry/lost/found                                       265
Stolen/Illegally owned gun{s} recovered during arrest/warrant                       232
Possession of gun by felon or prohibited person                                     170
Possession                                                                          158
                                                                                  ...
ShotSpotter                                                                           1
Home Invasion - Resident killed                                                       1
Officer Involved Shooting - subject/suspect/perpetrator surrender at standoff         1
Officer Involved Shooting - subject/suspect/perpetrator unarmed                       1
Self-Inflicted                                                                        1
Name: 8, Length: 83, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #9
------------------------------
0                                                                238729
Brandishing/flourishing/open carry/lost/found                       122
Stolen/Illegally owned gun{s} recovered during arrest/warrant       104
Possession of gun by felon or prohibited person                      92
Possession                                                           68
                                                                  ...
Workplace shooting                                                    1
Officer Involved Shooting - Bystander killed                          1
House party                                                           1
Officer Involved Shooting - subject/suspect/perpetrator shot          1
Sex crime involving firearm                                           1
Name: 9, Length: 68, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #10
------------------------------
0                                                                              239240
Brandishing/flourishing/open carry/lost/found                                      84
Possession of gun by felon or prohibited person                                    52
Stolen/Illegally owned gun{s} recovered during arrest/warrant                      48
Possession                                                                         33
Concealed Carry License - Victim                                                   16
Shootout                                                                           15
Gun stolen from owner                                                              15
Pistol-whipping                                                                    15
Armed robbery with injury/death and/or evidence of DGU found                       14
Assault weapon                                                                     12
Criminal act with stolen gun                                                       10
Officer Involved Shooting - Officer shot                                            8
ATF/LE Confiscation/Raid/Arrest                                                     8
School Shooting - elementary/secondary school                                       8
Child injured self                                                                  7
Domestic Violence                                                                   7
LOCKDOWN/ALERT ONLY: No GV Incident Occurred Onsite                                 7
Drug involvement                                                                    7
BB/Pellet/Replica gun                                                               6
Defensive Use - Stand Your Ground/Castle Doctrine established                       5
Kidnapping/abductions/hostage                                                       5
Under the influence of alcohol or drugs                                             4
School Incident                                                                     4
Mass Shooting                                                                       4
Concealed Carry License - Perpetrator                                               4
Officer Involved Shooting - subject/suspect/perpetrator suicide at standoff         3
Guns stolen from law enforcement                                                    3
Car-jacking                                                                         3
Defensive Use                                                                       3
 victim shoots subject/suspect/perpetrator                                          2
Defensive Use - WITHOUT a gun                                                       2
Child killed by child                                                               2
Implied Weapon                                                                      2
Child killed self                                                                   2
Child picked up & fired gun                                                         2
Terrorism Involvement                                                               1
Officer Involved Shooting - Shots fired                                             1
Home Invasion - subject/suspect/perpetrator killed                                  1
Bar/club incident - in or around establishment                                      1
Defensive Use - Good Samaritan/Third Party                                          1
Officer Involved Shooting - subject/suspect/perpetrator killed                      1
Sex crime involving firearm                                                         1
Drive-by                                                                            1
Spree Shooting                                                                      1
Defensive Use - Crime occurs                                                        1
 no death/injury - elementary/secondary school                                      1
Workplace shooting                                                                  1
Gun range/gun shop/gun show shooting                                                1
Gang involvement                                                                    1
Officer Involved Shooting - Bystander killed                                        1
Name: 10, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #11
------------------------------
0                                                                              239470
Brandishing/flourishing/open carry/lost/found                                      33
Stolen/Illegally owned gun{s} recovered during arrest/warrant                      29
Possession of gun by felon or prohibited person                                    21
Possession                                                                         15
Concealed Carry License - Victim                                                   13
Assault weapon                                                                     12
Gun stolen from owner                                                               9
Armed robbery with injury/death and/or evidence of DGU found                        9
Kidnapping/abductions/hostage                                                       7
Shootout                                                                            5
ATF/LE Confiscation/Raid/Arrest                                                     5
Pistol-whipping                                                                     4
Concealed Carry License - Perpetrator                                               4
Criminal act with stolen gun                                                        4
Child injured by child                                                              3
Gun range/gun shop/gun show shooting                                                3
LOCKDOWN/ALERT ONLY: No GV Incident Occurred Onsite                                 3
Domestic Violence                                                                   3
Under the influence of alcohol or drugs                                             2
BB/Pellet/Replica gun                                                               2
Car-jacking                                                                         2
School Shooting - university/college                                                2
School Shooting - elementary/secondary school                                       2
Spree Shooting                                                                      2
Officer Involved Shooting - subject/suspect/perpetrator suicide at standoff         1
Defensive Use                                                                       1
Drug involvement                                                                    1
Sex crime involving firearm                                                         1
Child killed self                                                                   1
 no injury                                                                          1
 victim shoots subject/suspect/perpetrator                                          1
Guns stolen from law enforcement                                                    1
Defensive Use - Shots fired                                                         1
Ghost gun                                                                           1
Gun shop robbery or burglary                                                        1
Defensive Use - Good Samaritan/Third Party                                          1
Mass Murder                                                                         1
Name: 11, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #12
------------------------------
0                                                                239578

Name: 13, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #14
------------------------------
0                                                                239659
Brandishing/flourishing/open carry/lost/found                         5
Stolen/Illegally owned gun{s} recovered during arrest/warrant         3
Domestic Violence                                                     2
Possession of gun by felon or prohibited person                       2
Gun stolen from owner                                                 1
Under the influence of alcohol or drugs                               1
Defensive Use - Stand Your Ground/Castle Doctrine established         1
Pistol-whipping                                                       1
Concealed Carry License - Victim                                      1
Guns stolen from law enforcement                                      1
Name: 14, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #15
------------------------------
0                                                                239666
Stolen/Illegally owned gun{s} recovered during arrest/warrant         3
Possession of gun by felon or prohibited person                       3
Brandishing/flourishing/open carry/lost/found                         3
Gun stolen from owner                                                 1
Criminal act with stolen gun                                          1
Name: 15, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #16
------------------------------
0                                                                239670
Stolen/Illegally owned gun{s} recovered during arrest/warrant         2
Assault weapon                                                        2
Ghost gun                                                             1
Gun stolen from owner                                                 1
Possession                                                            1
Name: 16, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #17
------------------------------
0                                                                239674
Stolen/Illegally owned gun{s} recovered during arrest/warrant         1
Gun stolen from owner                                                 1
Assault weapon                                                        1
Name: 17, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #18
------------------------------
0                                                                239676
Stolen/Illegally owned gun{s} recovered during arrest/warrant         1
Name: 18, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #19
------------------------------
0                                   239676
Concealed Carry License - Victim         1
Name: 19, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [8]:
# Renaming/Recategorizing Incidents in the original df, and then will split again
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Possession of gun by felon or prohibited person', 'Possession')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Shot - Wounded/Injured', 'Shooting')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Shots Fired - No Injuries', 'Shooting')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Shot - Dead', 'Shooting')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Accidental Shooting', 'Shooting')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Armed robbery with injury/death and/or evidence of DGU found', 'Armed robbery')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Bar/club incident - in or around establishment', 'Bar/club incident') 
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Officer Involved Shooting - subject/suspect/perpetrator killed', 'Officer Involved Incident') 
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Attempted Murder/Suicide', 'Murder/Suicide')   
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Home Invasion - Resident killed', 'Home Invasion') 
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Officer Involved Shooting - subject/suspect/perpetrator shot', 'Officer Involved Incident')  
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Officer Involved Shooting - Officer shot', 'Officer Involved Incident') 
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Officer Involved Shooting - Officer killed', 'Officer Involved Incident')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Officer Involved Shooting - Accidental discharge - no injury required', 'Officer Involved Incident')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('School Shooting - elementary/secondary school', 'School Shooting')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Suicide', 'Suicide/Attempt')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Suicide - Attempt', 'Suicide/Attempt')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Gun at school', 'School Incident')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Shots fired', 'Shooting')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Brandishing/flourishing/open carry/lost/found', 'Brandishing Gun')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Home Invasion - No death or injury', 'Home Invasion')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Home Invasion - Resident injured', 'Home Invasion')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Shooting - Injury', 'Shooting')
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Officer Involved Incident - Weapon involved but no shots fired', 'Officer Involved Incident') 
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace('Officer Involved Shooting - Shooting', 'Officer Involved Incident') 
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace(r'\s*,\s*', ',', regex=True) # removing spaces before and after commas
df['incident_characteristics'] = df['incident_characteristics']\
.str.replace(r'\s+', ' ', regex=True) # removing any extra number of spaces with only one space 
df['incident_characteristics'] = df['incident_characteristics']\
.str.strip() # removing spaces in the begining and end of the string

df.head()

,incident_id,date,state,n_killed,n_injured,incident_characteristics,latitude,longitude
0,461105,2013-01-01,Pennsylvania,0,4,"Shooting,Mass Shooting,Possession,Possession",40.3467,-79.8559
1,460726,2013-01-01,California,1,3,"Shooting,Shooting,Mass Shooting,Gang involvement",33.9090,-118.3330
2,478855,2013-01-01,Ohio,1,3,"Shooting,Shooting,Shooting,Bar/club incident",41.4455,-82.1377
3,478925,2013-01-05,Colorado,4,0,"Shooting,Officer Involved Incident,Officer Inv...",39.6518,-104.8020
4,478959,2013-01-07,North Carolina,2,2,"Shooting,Shooting,Suicide/Attempt,Murder/Suici...",36.1140,-79.9569

In [9]:
# Re-splitting and checking values in columns
df_split = df['incident_characteristics'].str.split(',', expand=True).fillna('0')
for i in range(0,20):
    print(f'Column #{i}')
    print('-' * 30)        
    print(df_split[i].value_counts()[0:10])
    print('~' * 50)

Column #0
------------------------------
Shooting                      174119
Non-Shooting Incident          41541
Armed robbery                   7528
Institution/Group/Business      4316
TSA Action                      2653
Possession                      1373
Brandishing Gun                 1350
Home Invasion                   1323
Drug involvement                1005
Gun stolen from owner            834
Name: 0, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #1
------------------------------
0                                  96995
Shooting                           16689
Officer Involved Incident          14419
Drive-by                           11873
Drug involvement                   11716
Home Invasion                       9829
Possession                          8332
Armed robbery                       6438
ATF/LE Confiscation/Raid/Arrest     5915
Domestic Violence                   5690
Name: 1, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #2
------------------------------
0                                  151892
Officer Involved Incident           14888
Possession                          13245
Home Invasion                        7700
ATF/LE Confiscation/Raid/Arrest      7543
Shooting                             6095
Brandishing Gun                      4453
Armed robbery                        2281
Murder/Suicide/Attempt               2268
School Incident                      2007
Name: 2, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #3
------------------------------
0                                  184639
Possession                          12974
Accidental/Negligent Discharge       3617
Brandishing Gun                      3514
Officer Involved Incident            2655
no injury                            2550
Defensive Use                        2382
Domestic Violence                    2155
ATF/LE Confiscation/Raid/Arrest      1683
Shooting                             1629
Name: 3, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #4
------------------------------
0                                                                208283
Possession                                                         6521
Brandishing Gun                                                    2189
Stolen/Illegally owned gun{s} recovered during arrest/warrant      1914
Accidental/Negligent Discharge                                     1759
Officer Involved Incident                                          1215
ATF/LE Confiscation/Raid/Arrest                                    1006
Defensive Use - Victim stops crime                                  940
Domestic Violence                                                   913
Self-Inflicted                                                      805
Name: 4, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #5
------------------------------
0                                                                222651
Possession                                                         2623
Stolen/Illegally owned gun{s} recovered during arrest/warrant      1536
Brandishing Gun                                                    1503
ATF/LE Confiscation/Raid/Arrest                                     842
Self-Inflicted                                                      759
victim shoots subject/suspect/perpetrator                           648
Domestic Violence                                                   570
Armed robbery                                                       543
Officer Involved Incident                                           445
Name: 5, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #6
------------------------------
0                                                                230774
Possession                                                         1550
Brandishing Gun                                                     875
Stolen/Illegally owned gun{s} recovered during arrest/warrant       816
victim shoots subject/suspect/perpetrator                           424
Armed robbery                                                       334
ATF/LE Confiscation/Raid/Arrest                                     309
Defensive Use - Stand Your Ground/Castle Doctrine established       250
Domestic Violence                                                   227
Officer Involved Incident                                           217
Name: 6, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #7
------------------------------
0                                                                235235
Possession                                                          770
Brandishing Gun                                                     505
Stolen/Illegally owned gun{s} recovered during arrest/warrant       410
Defensive Use - Stand Your Ground/Castle Doctrine established       253
Armed robbery                                                       193
ATF/LE Confiscation/Raid/Arrest                                     138
Child picked up & fired gun                                         137
Assault weapon                                                      131
Domestic Violence                                                   123
Name: 7, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #8
------------------------------
0                                                                237615
Possession                                                          328
Brandishing Gun                                                     265
Stolen/Illegally owned gun{s} recovered during arrest/warrant       232
Armed robbery                                                       105
Concealed Carry License - Victim                                     68
Child picked up & fired gun                                          62
ATF/LE Confiscation/Raid/Arrest                                      57
Domestic Violence                                                    57
Assault weapon                                                       54
Name: 8, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #9
------------------------------
0                                                                238729
Possession                                                          160
Brandishing Gun                                                     122
Stolen/Illegally owned gun{s} recovered during arrest/warrant       104
Armed robbery                                                        49
Concealed Carry License - Victim                                     36
ATF/LE Confiscation/Raid/Arrest                                      34
Assault weapon                                                       33
Child injured self                                                   32
Child killed self                                                    26
Name: 9, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #10
------------------------------
0                                                                239240
Possession                                                           85
Brandishing Gun                                                      84
Stolen/Illegally owned gun{s} recovered during arrest/warrant        48
Concealed Carry License - Victim                                     16
Pistol-whipping                                                      15
Gun stolen from owner                                                15
Shootout                                                             15
Armed robbery                                                        14
Assault weapon                                                       12
Name: 10, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #11
------------------------------
0                                                                239470
Possession                                                           36
Brandishing Gun                                                      33
Stolen/Illegally owned gun{s} recovered during arrest/warrant        29
Concealed Carry License - Victim                                     13
Assault weapon                                                       12
Armed robbery                                                         9
Gun stolen from owner                                                 9
Kidnapping/abductions/hostage                                         7
Shootout                                                              5
Name: 11, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #12
------------------------------
0                                                                239578
Stolen/Illegally owned gun{s} recovered during arrest/warrant        18
Possession                                                           18
Brandishing Gun                                                      15
Concealed Carry License - Victim                                      6
Assault weapon                                                        6
Kidnapping/abductions/hostage                                         4
Gun stolen from owner                                                 4
Criminal act with stolen gun                                          3
Concealed Carry License - Perpetrator                                 3
Name: 12, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #13
------------------------------
0                                                                239628
Stolen/Illegally owned gun{s} recovered during arrest/warrant        11
Brandishing Gun                                                       8
Possession                                                            7
Assault weapon                                                        5
Pistol-whipping                                                       3
BB/Pellet/Replica gun                                                 2
Car-jacking                                                           2
Armed robbery                                                         1
Gun stolen from owner                                                 1
Name: 13, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #14
------------------------------
0                                                                239659
Brandishing Gun                                                       5
Stolen/Illegally owned gun{s} recovered during arrest/warrant         3
Domestic Violence                                                     2
Possession                                                            2
Gun stolen from owner                                                 1
Defensive Use - Stand Your Ground/Castle Doctrine established         1
Pistol-whipping                                                       1
Under the influence of alcohol or drugs                               1
Concealed Carry License - Victim                                      1
Name: 14, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #15
------------------------------
0                                                                239666
Stolen/Illegally owned gun{s} recovered during arrest/warrant         3
Possession                                                            3
Brandishing Gun                                                       3
Gun stolen from owner                                                 1
Criminal act with stolen gun                                          1
Name: 15, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #16
------------------------------
0                                                                239670
Stolen/Illegally owned gun{s} recovered during arrest/warrant         2
Assault weapon                                                        2
Ghost gun                                                             1
Gun stolen from owner                                                 1
Possession                                                            1
Name: 16, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #17
------------------------------
0                                                                239674
Stolen/Illegally owned gun{s} recovered during arrest/warrant         1
Gun stolen from owner                                                 1
Assault weapon                                                        1
Name: 17, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #18
------------------------------
0                                                                239676
Stolen/Illegally owned gun{s} recovered during arrest/warrant         1
Name: 18, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Column #19
------------------------------
0                                   239676
Concealed Carry License - Victim         1
Name: 19, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [10]:
# Categories keeping
catgories = ['Shooting', 'Armed robbery', 'Possession', 'Home Invasion', 'Drug involvement', 'Officer Involved Incident',
       'Car-jacking', 'Animal shot/killed','Domestic Violence', 'Gang involvement', 'School Incident', 'Drive-by',
       'Brandishing Gun', 'Institution/Group/Business', 'TSA Action']

# looping through the categoy list to create new 0/1 columns

for catg in catgories:
    
    # setting default value of new column to 0
    df_split[catg] = 0
    
    # looping through the splitted columns
    for i in range(0,20): 
        
        # if the value of the column equals the catg name, swtich the new category value to 1
        df_split.loc[df_split[i] == catg, catg] = 1  
        
df_split.head()

,0,1,2,3,4,5,6,7,8,9,...,Officer Involved Incident,Car-jacking,Animal shot/killed,Domestic Violence,Gang involvement,School Incident,Drive-by,Brandishing Gun,Institution/Group/Business,TSA Action
0,Shooting,Mass Shooting,Possession,Possession,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Shooting,Shooting,Mass Shooting,Gang involvement,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,Shooting,Shooting,Shooting,Bar/club incident,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Shooting,Officer Involved Incident,Officer Involved Incident,Drug involvement,Kidnapping/abductions/hostage,Under the influence of alcohol or drugs,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,Shooting,Shooting,Suicide/Attempt,Murder/Suicide/Attempt,Murder/Suicide/Attempt,Domestic Violence,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [11]:
# checking the new values
for catg in catgories:
    print(f'category: {catg}')
    print('-' * 50)
    print(df_split[catg].value_counts())
    print('~' * 50)

category: Shooting
--------------------------------------------------
1    175725
0     63952
Name: Shooting, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Armed robbery
--------------------------------------------------
0    219954
1     19723
Name: Armed robbery, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Possession
--------------------------------------------------
0    200625
1     39052
Name: Possession, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Home Invasion
--------------------------------------------------
0    229036
1     10641
Name: Home Invasion, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Drug involvement
--------------------------------------------------
0    222578
1     17099
Name: Drug involvement, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Officer Involved Incident
--------------------------------------------------
0    221689
1     17988
Name: Officer Involved Incident, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Car-jacking
--------------------------------------------------
0    234733
1      4944
Name: Car-jacking, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Animal shot/killed
--------------------------------------------------
0    238954
1       723
Name: Animal shot/killed, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Domestic Violence
--------------------------------------------------
0    228836
1     10841
Name: Domestic Violence, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Gang involvement
--------------------------------------------------
0    234000
1      5677
Name: Gang involvement, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: School Incident
--------------------------------------------------
0    236872
1      2805
Name: School Incident, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Drive-by
--------------------------------------------------
0    226022
1     13655
Name: Drive-by, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Brandishing Gun
--------------------------------------------------
0    220660
1     19017
Name: Brandishing Gun, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: Institution/Group/Business
--------------------------------------------------
0    228631
1     11046
Name: Institution/Group/Business, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
category: TSA Action
--------------------------------------------------
0    234641
1      5036
Name: TSA Action, dtype: int64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [12]:
# Dropping the original columns
cols_to_drop = range(0, 20)
df_split.drop(columns=cols_to_drop, inplace=True)
df_split.head()

,Shooting,Armed robbery,Possession,Home Invasion,Drug involvement,Officer Involved Incident,Car-jacking,Animal shot/killed,Domestic Violence,Gang involvement,School Incident,Drive-by,Brandishing Gun,Institution/Group/Business,TSA Action
0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [13]:
# Concatenate the split columns with the original DataFrame
violence_df = pd.concat([df, df_split], axis=1)
violence_df.head()

,incident_id,date,state,n_killed,n_injured,incident_characteristics,latitude,longitude,Shooting,Armed robbery,...,Officer Involved Incident,Car-jacking,Animal shot/killed,Domestic Violence,Gang involvement,School Incident,Drive-by,Brandishing Gun,Institution/Group/Business,TSA Action
0,461105,2013-01-01,Pennsylvania,0,4,"Shooting,Mass Shooting,Possession,Possession",40.3467,-79.8559,1,0,...,0,0,0,0,0,0,0,0,0,0
1,460726,2013-01-01,California,1,3,"Shooting,Shooting,Mass Shooting,Gang involvement",33.9090,-118.3330,1,0,...,0,0,0,0,1,0,0,0,0,0
2,478855,2013-01-01,Ohio,1,3,"Shooting,Shooting,Shooting,Bar/club incident",41.4455,-82.1377,1,0,...,0,0,0,0,0,0,0,0,0,0
3,478925,2013-01-05,Colorado,4,0,"Shooting,Officer Involved Incident,Officer Inv...",39.6518,-104.8020,1,0,...,1,0,0,0,0,0,0,0,0,0
4,478959,2013-01-07,North Carolina,2,2,"Shooting,Shooting,Suicide/Attempt,Murder/Suici...",36.1140,-79.9569,1,0,...,0,0,0,1,0,0,0,0,0,0

In [14]:
# Dropping the incident_characteristics column
violence_df.drop(columns="incident_characteristics", inplace=True)
violence_df.head()

,incident_id,date,state,n_killed,n_injured,latitude,longitude,Shooting,Armed robbery,Possession,...,Officer Involved Incident,Car-jacking,Animal shot/killed,Domestic Violence,Gang involvement,School Incident,Drive-by,Brandishing Gun,Institution/Group/Business,TSA Action
0,461105,2013-01-01,Pennsylvania,0,4,40.3467,-79.8559,1,0,1,...,0,0,0,0,0,0,0,0,0,0
1,460726,2013-01-01,California,1,3,33.9090,-118.3330,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2,478855,2013-01-01,Ohio,1,3,41.4455,-82.1377,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,478925,2013-01-05,Colorado,4,0,39.6518,-104.8020,1,0,0,...,1,0,0,0,0,0,0,0,0,0
4,478959,2013-01-07,North Carolina,2,2,36.1140,-79.9569,1,0,0,...,0,0,0,1,0,0,0,0,0,0

In [15]:
violence_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239677 entries, 0 to 239676
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   incident_id                 239677 non-null  int64
 1   date                        239677 non-null  object
 2   state                       239677 non-null  object
 3   n_killed                    239677 non-null  int64
 4   n_injured                   239677 non-null  int64
 5   latitude                    231754 non-null  float64
 6   longitude                   231754 non-null  float64
 7   Shooting                    239677 non-null  int64
 8   Armed robbery               239677 non-null  int64
 9   Possession                  239677 non-null  int64
 10  Home Invasion               239677 non-null  int64
 11  Drug involvement            239677 non-null  int64
 12  Officer Involved Incident   239677 non-null  int64
 13  Car-jacking                 239677 non-null  int64
 14  Animal shot/killed          239677 non-null  int64
 15  Domestic Violence           239677 non-null  int64
 16  Gang involvement            239677 non-null  int64
 17  School Incident             239677 non-null  int64
 18  Drive-by                    239677 non-null  int64
 19  Brandishing Gun             239677 non-null  int64
 20  Institution/Group/Business  239677 non-null  int64
 21  TSA Action                  239677 non-null  int64
dtypes: float64(2), int64(18), object(2)
memory usage: 40.2+ MB

In [19]:
# Changing date column to datetime format
violence_df['date'] = pd.to_datetime(violence_df['date'])
violence_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239677 entries, 0 to 239676
Data columns (total 22 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   incident_id                 239677 non-null  int64
 1   date                        239677 non-null  datetime64[ns]
 2   state                       239677 non-null  object
 3   n_killed                    239677 non-null  int64
 4   n_injured                   239677 non-null  int64
 5   latitude                    231754 non-null  float64
 6   longitude                   231754 non-null  float64
 7   Shooting                    239677 non-null  int64
 8   Armed robbery               239677 non-null  int64
 9   Possession                  239677 non-null  int64
 10  Home Invasion               239677 non-null  int64
 11  Drug involvement            239677 non-null  int64
 12  Officer Involved Incident   239677 non-null  int64
 13  Car-jacking                 239677 non-null  int64
 14  Animal shot/killed          239677 non-null  int64
 15  Domestic Violence           239677 non-null  int64
 16  Gang involvement            239677 non-null  int64
 17  School Incident             239677 non-null  int64
 18  Drive-by                    239677 non-null  int64
 19  Brandishing Gun             239677 non-null  int64
 20  Institution/Group/Business  239677 non-null  int64
 21  TSA Action                  239677 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(18), object(1)
memory usage: 40.2+ MB

In [20]:
# extracting the year and the month as new columns
violence_df['year'] = violence_df['date'].dt.year
violence_df['month'] = violence_df['date'].dt.month_name()
violence_df.tail()

,incident_id,date,state,n_killed,n_injured,latitude,longitude,Shooting,Armed robbery,Possession,...,Animal shot/killed,Domestic Violence,Gang involvement,School Incident,Drive-by,Brandishing Gun,Institution/Group/Business,TSA Action,year,month
239672,1083142,2018-03-31,Louisiana,0,0,NaN,NaN,1,0,0,...,0,0,0,0,0,0,0,0,2018,March
239673,1083139,2018-03-31,Louisiana,1,0,31.7537,-93.0836,1,0,0,...,0,0,0,0,0,0,1,0,2018,March
239674,1083151,2018-03-31,Louisiana,0,1,29.9239,-90.0442,1,0,0,...,0,0,0,0,0,0,0,0,2018,March
239675,1082514,2018-03-31,Texas,1,0,29.7201,-95.6110,1,0,0,...,0,0,0,0,0,0,0,0,2018,March
239676,1081940,2018-03-31,Maine,2,0,44.7293,-69.7691,1,0,0,...,0,1,0,0,0,0,0,0,2018,March

In [22]:
# Total number of victims
violence_df['n_killed_or_injured'] = violence_df['n_killed'] + violence_df['n_injured'] 
violence_df.tail()

,incident_id,date,state,n_killed,n_injured,latitude,longitude,Shooting,Armed robbery,Possession,...,Domestic Violence,Gang involvement,School Incident,Drive-by,Brandishing Gun,Institution/Group/Business,TSA Action,year,month,n_killed_or_injured
239672,1083142,2018-03-31,Louisiana,0,0,NaN,NaN,1,0,0,...,0,0,0,0,0,0,0,2018,March,0
239673,1083139,2018-03-31,Louisiana,1,0,31.7537,-93.0836,1,0,0,...,0,0,0,0,0,1,0,2018,March,1
239674,1083151,2018-03-31,Louisiana,0,1,29.9239,-90.0442,1,0,0,...,0,0,0,0,0,0,0,2018,March,1
239675,1082514,2018-03-31,Texas,1,0,29.7201,-95.6110,1,0,0,...,0,0,0,0,0,0,0,2018,March,1
239676,1081940,2018-03-31,Maine,2,0,44.7293,-69.7691,1,0,0,...,1,0,0,0,0,0,0,2018,March,2

In [23]:
# Getting list of column names 
violence_df.columns.to_list()

['incident_id',
 'date',
 'state',
 'n_killed',
 'n_injured',
 'latitude',
 'longitude',
 'Shooting',
 'Armed robbery',
 'Possession',
 'Home Invasion',
 'Drug involvement',
 'Officer Involved Incident',
 'Car-jacking',
 'Animal shot/killed',
 'Domestic Violence',
 'Gang involvement',
 'School Incident',
 'Drive-by',
 'Brandishing Gun',
 'Institution/Group/Business',
 'TSA Action',
 'year',
 'month',
 'n_killed_or_injured']

In [24]:
# Define the desired column order
column_order = ['incident_id', 'date','year','month','state', 'latitude', 'longitude',
                'n_killed', 'n_injured', 'n_killed_or_injured', 
                'Shooting', 'Armed robbery', 'Possession', 'Home Invasion', 'Drug involvement',
                'Officer Involved Incident', 'Car-jacking', 'Animal shot/killed',
                'Domestic Violence', 'Gang involvement', 'School Incident', 'Drive-by',
                'Brandishing Gun', 'Institution/Group/Business', 'TSA Action']
# Reorder the columns in the DataFrame
violence_df = violence_df.reindex(columns=column_order)
violence_df.head()

,incident_id,date,year,month,state,latitude,longitude,n_killed,n_injured,n_killed_or_injured,...,Officer Involved Incident,Car-jacking,Animal shot/killed,Domestic Violence,Gang involvement,School Incident,Drive-by,Brandishing Gun,Institution/Group/Business,TSA Action
0,461105,2013-01-01,2013,January,Pennsylvania,40.3467,-79.8559,0,4,4,...,0,0,0,0,0,0,0,0,0,0
1,460726,2013-01-01,2013,January,California,33.9090,-118.3330,1,3,4,...,0,0,0,0,1,0,0,0,0,0
2,478855,2013-01-01,2013,January,Ohio,41.4455,-82.1377,1,3,4,...,0,0,0,0,0,0,0,0,0,0
3,478925,2013-01-05,2013,January,Colorado,39.6518,-104.8020,4,0,4,...,1,0,0,0,0,0,0,0,0,0
4,478959,2013-01-07,2013,January,North Carolina,36.1140,-79.9569,2,2,4,...,0,0,0,1,0,0,0,0,0,0

In [25]:
# exporting the cleaned data to csv
violence_df.to_csv("../Resources/gun_violence_2013to2018_cleaned.csv", encoding="utf-8", index=False, header=True)